// ============================================================
// RADICALS & CHARACTER DECOMPOSITION DATABASE
// Cung cấp thông tin giải nghĩa bộ thủ bằng tiếng Việt
// và phân tích các thành phần cho các chữ Hán thông dụng.
// ============================================================

export const RADICALS_DICT = {
  // Bộ 1 nét
  '一': 'Nhất (Một)',
  '丨': 'Cổn (Đường sổ thẳng)',
  '丶': 'Chủ (Chấm nhỏ)',
  '丿': 'Phiệt (Nét phẩy)',
  '乙': 'Ất (Vị trí thứ hai)',
  '亅': 'Quyết (Nét móc)',
  // Bộ 2 nét
  '二': 'Nhị (Hai)',
  '亠': 'Đầu (Mái che)',
  '人': 'Nhân (Người)',
  '亻': 'Nhân (Người - dạng đứng)',
  '儿': 'Nhân đi (Người đi)',
  '入': 'Nhập (Vào)',
  '八': 'Bát (Tám)',
  '冂': 'Quynh (Vùng biên cảnh)',
  '冖': 'Mịch (Mái che, khăn phủ)',
  '冫': 'Băng (Băng tuyết, lạnh)',
  '几': 'Kỷ (Cái ghế nhỏ, cái bàn)',
  '凵': 'Khảm (Vùng đất trũng)',
  '刀': 'Đao (Con dao)',
  '刂': 'Đao (Con dao - dạng bên)',
  '力': 'Lực (Sức lực)',
  '勹': 'Bao (Bao bọc)',
  '匕': 'Chủy (Cái thìa)',
  '匚': 'Khuông (Đồ đựng)',
  '匸': 'Hệ (Che đậy)',
  '十': 'Thập (Mười)',
  '卜': 'Bốc (Bói toán)',
  '卩': 'Tiết (Đốt tre, lệnh bài)',
  '厂': 'Hán (Sườn núi)',
  '厶': 'Tư (Riêng tư)',
  '又': 'Hựu (Lại nữa, bàn tay)',
  // Bộ 3 nét
  '口': 'Khẩu (Cái miệng)',
  '囗': 'Vi (Vây quanh)',
  '土': 'Thổ (Đất)',
  '士': 'Sĩ (Kẻ sĩ, học giả)',
  '夂': 'Truy (Đi chậm)',
  '夕': 'Tịch (Hoàng hôn, đêm tối)',
  '大': 'Đại (To lớn)',
  '女': 'Nữ (Phụ nữ, con gái)',
  '子': 'Tử (Con cái, đứa trẻ)',
  '宀': 'Miên (Mái nhà)',
  '寸': 'Thốn (Tấc, đo lường)',
  '小': 'Tiểu (Nhỏ bé)',
  '⺌': 'Tiểu (Nhỏ bé - biến thể đầu)',
  '尢': 'Uông (Què quặt)',
  '尸': 'Thi (Xác chết, vai trò)',
  '屮': 'Triệt (Mầm non mới mọc)',
  '山': 'Sơn (Núi non)',
  '巛': 'Xuyên (Sông ngòi)',
  '工': 'Công (Công việc, thợ)',
  '己': 'Kỷ (Bản thân mình)',
  '巾': 'Cân (Cái khăn, vải)',
  '干': 'Can (Thiên can, khô ráo)',
  '幺': 'Yêu (Nhỏ nhắn, sợi tơ)',
  '广': 'Nghiễm (Mái nhà bên núi)',
  '廴': 'Dẫn (Bước đi dài)',
  '廾': 'Củng (Chắp tay nâng lên)',
  '弋': 'Dực (Bắn cung, chiếm lấy)',
  '弓': 'Cung (Cái cung bắn tên)',
  '彐': 'Ký (Đầu con heo)',
  '彑': 'Ký (Đầu con heo)',
  '彡': 'Sâm (Lông tóc dài, hoa văn)',
  '彳': 'Xích (Bước ngắn chân trái)',
  '忄': 'Tâm (Tấm lòng, cảm xúc - dạng đứng)',
  '扌': 'Thủ (Bàn tay, hành động - dạng đứng)',
  // Bộ 4 nét
  '心': 'Tâm (Tấm lòng, tim)',
  '戈': 'Qua (Cây mâu, binh khí)',
  '户': 'Hộ (Cánh cửa, gia đình)',
  '手': 'Thủ (Bàn tay)',
  '支': 'Chi (Cành cây, chi nhánh)',
  '攵': 'Phộc (Đánh nhẹ, gõ - dạng đứng)',
  '文': 'Văn (Văn chương, chữ viết)',
  '斗': 'Đấu (Đấu đong gạo)',
  '斤': 'Cân (Cái búa, rìu, cân)',
  '方': 'Phương (Phương hướng, vuông)',
  '无': 'Vô (Không có)',
  '日': 'Nhật (Mặt trời, ngày)',
  '曰': 'Viết (Nói rằng)',
  '月': 'Nguyệt (Mặt trăng, tháng)',
  '⺼': 'Nhục (Thịt - biến thể viết giống Nguyệt)',
  '木': 'Mộc (Cây cối, gỗ)',
  '欠': 'Khiếm (Thiếu thốn, ngáp)',
  '止': 'Chỉ (Dừng lại)',
  '歹': 'Ngạt (Xấu xa, tệ hại)',
  '殳': 'Thù (Binh khí dài)',
  '毋': 'Vô (Chớ, đừng)',
  '比': 'Tỷ (So sánh, kề bên)',
  '毛': 'Mao (Lông tóc)',
  '氏': 'Thị (Họ tộc)',
  '气': 'Khí (Hơi nước, không khí)',
  '水': 'Thủy (Nước)',
  '氵': 'Thủy (Nước - dạng đứng)',
  '火': 'Hỏa (Lửa)',
  '灬': 'Hỏa (Lửa - dạng dưới)',
  '爪': 'Trảo (Móng vuốt)',
  '爫': 'Trảo (Móng vuốt - dạng đầu)',
  '父': 'Phụ (Người cha)',
  '爻': 'Hào (Hào trong Kinh Dịch)',
  '爿': 'Tường (Mảnh gỗ bên trái)',
  '片': 'Phiến (Mảnh gỗ bên phải)',
  '牙': 'Nha (Răng thú)',
  '牛': 'Ngưu (Con trâu, bò)',
  '牜': 'Ngưu (Con trâu - dạng đứng)',
  '犬': 'Khuyển (Con chó)',
  '犭': 'Khuyển (Con chó - dạng đứng)',
  // Bộ 5 nét
  '玄': 'Huyền (Huyền bí, màu đen)',
  '玉': 'Ngọc (Viên ngọc)',
  '王': 'Vương (Vua, ngọc)',
  '瓜': 'Qua (Quả dưa)',
  '瓦': 'Ngõa (Ngói lợp)',
  '甘': 'Cam (Ngọt ngào)',
  '生': 'Sinh (Sinh sống, sinh sản)',
  '用': 'Dụng (Sử dụng)',
  '田': 'Điền (Ruộng đất)',
  '疋': 'Thất (Cuộn vải)',
  '疒': 'Nạch (Bệnh tật)',
  '癶': 'Bát (Đi hai hàng chân)',
  '白': 'Bạch (Màu trắng)',
  '皮': 'Bì (Da thú, vỏ ngoài)',
  '皿': 'Mãnh (Bát đĩa, đồ đựng)',
  '目': 'Mục (Mắt, nhìn)',
  '矛': 'Mâu (Cây thương, qua)',
  '矢': 'Thỉ (Mũi tên)',
  '石': 'Thạch (Đá)',
  '示': 'Thị (Thờ cúng, tổ tiên)',
  '礻': 'Thị (Thờ cúng - dạng đứng)',
  '禸': 'Nhựu (Vết chân dã thú)',
  '禾': 'Hòa (Cây lúa)',
  '穴': 'Huyệt (Hang động, lỗ hổng)',
  '立': 'Lập (Đứng vững, thiết lập)',
  // Bộ 6 nét trở lên
  '竹': 'Trúc (Cây tre, trúc)',
  '⺮': 'Trúc (Cây tre - biến thể đầu)',
  '米': 'Mễ (Gạo, ngũ cốc)',
  '糸': 'Mịch (Sợi tơ, tơ lụa)',
  '纟': 'Mịch (Sợi tơ - dạng giản thể)',
  '缶': 'Phẫu (Đồ sành sứ)',
  '网': 'Võng (Cái lưới)',
  '罒': 'Võng (Cái lưới - dạng trên)',
  '羊': 'Dương (Con dê, cừu)',
  '羽': 'Vũ (Lông vũ, cánh chim)',
  '老': 'Lão (Người già)',
  '而': 'Nhi (Râu dưới cằm, mà)',
  '耒': 'Lỗi (Cái cày ruộng)',
  '耳': 'Nhĩ (Cái tai, nghe)',
  '聿': 'Duật (Cây bút viết)',
  '肉': 'Nhục (Thịt)',
  '臣': 'Thần (Bầy tôi, tôi tớ)',
  '自': 'Tự (Bản thân mình, từ đâu)',
  '至': 'Chí (Đạt đến, đạt cực điểm)',
  '臼': 'Cữu (Cái cối giã gạo)',
  '舌': '舌 (Cái lưỡi)',
  '舛': 'Suyễn (Sai lệch, nhầm lẫn)',
  '舟': 'Chu (Chiếc thuyền)',
  '艮': 'Cấn (Bền vững, quẻ Cấn)',
  '色': 'Sắc (Màu sắc, vẻ mặt)',
  '艹': 'Thảo (Cỏ cây, thảo mộc)',
  '虍': 'Hô (Vằn da hổ)',
  '虫': 'Trùng (Sâu bọ, côn trùng)',
  '血': 'Huyết (Máu)',
  '行': 'Hành (Đi lại, thi hành)',
  '衣': 'Y (Quần áo)',
  '衤': 'Y (Quần áo - dạng đứng)',
  '见': 'Kiến (Nhìn thấy, gặp gỡ)',
  '角': 'Giác (Sừng thú, góc)',
  '讠': 'Ngôn (Lời nói, ngôn từ)',
  '谷': 'Cốc (Khe núi, thung lũng)',
  '豆': 'Đậu (Hạt đậu, cái thố)',
  '豕': 'Thỉ (Con heo, lợn)',
  '豸': 'Trĩ (Loài dã thú không sừng)',
  '贝': 'Bối (Vỏ sò, tiền tệ, của báu)',
  '赤': 'Xích (Màu đỏ)',
  '走': 'Tẩu (Đi, chạy)',
  '⻊': 'Túc (Bàn chân, đi lại)',
  '身': 'Thân (Thân thể, mình)',
  '车': 'Xa (Chiếc xe, cỗ xe)',
  '辛': 'Tân (Cay đắng, vất vả)',
  '辰': 'Thần (Giờ Thìn, thiên thể)',
  '辶': 'Sước (Chợt đi chợt dừng, bộ sước)',
  '阝': 'Phụ / Ấp (Gò đất hoặc Vùng đất)',
  '酉': 'Dậu (Bình rượu, giờ Dậu)',
  '里': 'Lý (Làng mạc, dặm đường)',
  '接口': 'Tiếp khẩu',
  '钅': 'Kim (Kim loại, tiền vàng)',
  '长': 'Trường (Dài, lớn tuổi)',
  '门': 'Môn (Cánh cửa)',
  '隹': 'Chuy (Chim đuôi ngắn)',
  '雨': 'Vũ (Mưa)',
  '青': 'Thanh (Xanh lục, xanh lam)',
  '非': 'Phi (Không phải, sai trái)',
  '面': 'Diện (Khuôn mặt, bề mặt)',
  '革': 'Cách (Da thuộc, cải cách)',
  '韦': 'Vi (Da thuộc mềm)',
  '音': 'Âm (Âm thanh, tiếng động)',
  '页': 'Hiệt (Trang giấy, đầu)',
  '风': 'Phong (Gió)',
  '飞': 'Phi (Bay lượn)',
  '饣': 'Thực (Ăn uống, thức ăn)',
  '香': 'Hương (Mùi thơm)',
  '马': 'Mã (Con ngựa)',
  '骨': 'Cốt (Xương cốt)',
  '高': 'Cao (Cao lớn)',
  '鬼': 'Quỷ (Ma quỷ)',
  '鱼': 'Ngư (Con cá)',
  '鸟': 'Điểu (Con chim đuôi dài)',
  '麦': 'Mạch (Lúa mạch)',
  '黄': 'Hoàng (Màu vàng)',
  '黑': 'Hắc (Màu đen)',
  '齿': 'Xỉ (Răng)',
  '龙': 'Long (Con rồng)',
  '龟': 'Quy (Con rùa)',
  
  // Các chữ/bộ bổ sung phổ biến làm thành phần
  '也': 'Dã (Cũng, trợ từ cổ)',
  '巴': 'Ba (Mong đợi, dính bám)',
  '五': 'Ngũ (Số năm)',
  '不': 'Bất (Không)',
  '与': 'Dữ (Cùng với, cho)',
  '各': 'Các (Mỗi người, các nơi)',
  '占': 'Chiếm (Chiếm giữ, bói toán)',
  '交': 'Giao (Giao nhau, kết giao)',
  '头': 'Đầu (Cái đầu - giản thể)',
  '京': 'Kinh (Kinh đô, to lớn)',
  '反': 'Phản (Ngược lại, phản đối)',
  '采': 'Thải (Hái, chọn)',
  '奇': 'Kỳ (Kỳ lạ)',
  '由': 'Do (Nguyên nhân, tự do)',
  '化': 'Hóa (Biến hóa)',
  '早': 'Tảo (Sớm, buổi sáng)',
  '委': 'Ủy (Giao phó, ủy thác)',
  '半': 'Bán (Một nửa)',
  '叟': 'Sưu (Ông già)',
  '令': 'Lệnh (Mệnh lệnh, khiến cho)',
  '争': 'Tranh (Tranh giành, đấu tranh)',
  '曼': 'Mạn (Dài, rộng lớn)',
  '昔': 'Tích (Ngày xưa, thuở trước)',
};

export const CHAR_COMPONENTS_DICT = {
  '我': ['丿', '戈'],
  '你': ['亻', '尔'],
  '他': ['亻', '少', '也'],
  '她': ['女', '也'],
  '它': ['宀', '匕'],
  '们': ['亻', '门'],
  '这': ['辶', '文'],
  '那': ['阝'],
  '是': ['日', '疋'],
  '在': ['土'],
  '有': ['月'],
  '没': ['氵', '殳'],
  '好': ['女', '子'],
  '大': ['大'],
  '小': ['小'],
  '多': ['夕', '夕'],
  '少': ['小', '丿'],
  '猫': ['犭', '苗'],
  '狗': ['犭', '句'],
  '家': ['宀', '豕'],
  '国': ['囗', '玉'],
  '中': ['口', '丨'],
  '华': ['亻', '匕', '十'],
  '爸': ['父', '巴'],
  '妈': ['女', '马'],
  '汉': ['氵', '又'],
  '语': ['讠', '五', '口'],
  '书': ['乛', '丨', '丶'],
  '哥': ['口', '可'],
  '姐': ['女', '且'],
  '妹': ['女', '未'],
  '弟': ['弓', '丿'],
  '谢': ['讠', '身', '寸'],
  '客': ['宀', '各'],
  '气': ['气'],
  '校': ['木', '交'],
  '医': ['匚', '矢'],
  '生': ['生'],
  '师': ['巾'],
  '学': ['⺌', '冖', '子'],
  '习': ['⺄'],
  '院': ['阝', '完'],
  '商': ['亠', '丷', '口'],
  '店': ['广', '占'],
  '买': ['乛', '头'],
  '卖': ['十', '买'],
  '车': ['车'],
  '站': ['立', '占'],
  '机': ['木', '几'],
  '场': ['土'],
  '路': ['⻊', '各'],
  '飞': ['飞'],
  '电': ['日', '乚'],
  '影': ['日', '京', '彡'],
  '视': ['礻', '见'],
  '脑': ['⺼', '㐫'],
  '话': ['讠', '舌'],
  '信': ['亻', '言'],
  '钱': ['钅', '戋'],
  '杯': ['木', '不'],
  '茶': ['艹', '人', '木'],
  '米': ['米'],
  '饭': ['饣', '反'],
  '菜': ['艹', '采'],
  '肉': ['肉'],
  '果': ['日', '木'],
  '面': ['面'],
  '条': ['夂', '木'],
  '谁': ['讠', '隹'],
  '什': ['亻', '十'],
  '么': ['丿', '厶'],
  '怎': ['乍', '心'],
  '的': ['白', '勺'],
  '了': ['乛', '亅'],
  '哪': ['口', '那'],
  '奶': ['女', '乃'],
  '星': ['日', '生'],
  '期': ['其', '月'],
  '漂': ['氵', '票'],
  '亮': ['亠', '口', '冖', '儿'],
  '喜': ['士', '口', '丷', '口'],
  '欢': ['又', '欠'],
  '认': ['讠', '人'],
  '识': ['讠', '只'],
  '作': ['亻', '乍'],
  '同': ['冂', '一', '口'],
  '朋': ['月', '月'],
  '友': ['𠂇', '又'],
  '再': ['一', '冂', '土'],
  '后': ['厂', '一', '口'],
  '前': ['丷', '一', '月', '刂'],
  '早': ['日', '十'],
  '岁': ['山', '夕'],
  '点': ['占', '灬'],
  '苹': ['艹', '平'],
  '包': ['勹', '巳'],
  '衣': ['衣'],
  '服': ['⺼', '卩', '又'],
  '本': ['木', '一'],
  '笔': ['⺮', '毛'],
  '桌': ['卜', '日', '木'],
  '椅': ['木', '奇'],
  '钟': ['钅', '中'],
  '表': ['土', '衣'],
  '字': ['宀', '子'],
  '画': ['一', '由', '凵'],
  '报': ['扌', '卩', '又'],
  '纸': ['纟', '氏'],
  '天': ['一', '大'],
  '地': ['土', '也'],
  '风': ['几', '乂'],
  '雨': ['雨'],
  '云': ['二', '厶'],
  '雪': ['雨', '彐'],
  '花': ['艹', '化'],
  '草': ['艹', '早'],
  '树': ['木', '寸'],
  '河': ['氵', '可'],
  '海': ['氵', '每'],
  '山': ['山'],
  '石': ['石'],
  '红': ['纟', '工'],
  '绿': ['纟', '录'],
  '蓝': ['艹', '监'],
  '黄': ['黄'],
  '白': ['白'],
  '黑': ['黑'],
  '高': ['高'],
  '矮': ['矢', '委'],
  '胖': ['⺼', '半'],
  '瘦': ['疒', '叟'],
  '长': ['长'],
  '短': ['矢', '豆'],
  '新': ['立', '木', '斤'],
  '旧': ['丨', '日'],
  '明': ['日', '月'],
  '暗': ['日', '音'],
  '冷': ['冫', '令'],
  '热': ['灬'],
  '干': ['干'],
  '湿': ['氵', '显'],
  '脏': ['⺼', '庄'],
  '净': ['冫', '争'],
  '快': ['忄', '夬'],
  '慢': ['忄', '曼'],
  '难': ['又', '隹'],
  '易': ['日', '勿'],
  '对': ['又', '寸'],
  '错': ['钅', '昔'],
  '真': ['十', '目', '八'],
  '假': ['亻'],
  '人': ['人'],
  '口': ['口'],
  '女': ['女'],
  '子': ['子'],
  '宀': ['宀'],
  '日': ['日'],
  '月': ['月'],
  '木': ['木'],
  '土': ['土'],
  // 山 / 石 / 雨 đã có ở nhóm từ vựng thiên nhiên phía trên, không lặp lại ở đây.
  '水': ['水'],
  '火': ['火'],
  '心': ['心'],
  '手': ['手'],
  '门': ['门'],
  '立': ['立'],
  '纟': ['纟'],
  '钅': ['钅'],
  '饣': ['饣'],
  '辶': ['辶'],
  '讠': ['讠'],
  '艹': ['艹'],
  '犭': ['犭'],
  '忄': ['忄'],
  '扌': ['扌'],
  '彳': ['彳'],
  '阝': ['阝'],
};

// Hàm phân tích động bộ thủ và thành phần cho một từ bất kỳ
export function resolveDecompositions(wordStr, fallbackRadical) {
  const result = [];
  const seenRadicals = new Set();

  // Bỏ qua ký tự không phải chữ Hán
  const chars = (wordStr || '').split('').filter(c => /[\u4e00-\u9fa5]/.test(c));

  // 1. Phân tích từng chữ đơn trong từ
  chars.forEach(char => {
    const comps = CHAR_COMPONENTS_DICT[char] || [];
    if (comps.length > 0) {
      comps.forEach(comp => {
        if (!seenRadicals.has(comp)) {
          seenRadicals.add(comp);
          result.push({
            radical: comp,
            meaning: RADICALS_DICT[comp] || comp
          });
        }
      });
    } else {
      // Nếu không có decomposition cho chữ này, lấy chính chữ đó làm thành phần nếu nó là bộ thủ
      if (RADICALS_DICT[char] && !seenRadicals.has(char)) {
        seenRadicals.add(char);
        result.push({
          radical: char,
          meaning: RADICALS_DICT[char]
        });
      }
    }
  });

  // 2. Nếu sau khi phân tích vẫn rỗng, bổ sung fallbackRadical từ DB
  if (result.length === 0 && fallbackRadical) {
    const rawRad = fallbackRadical.trim();
    if (rawRad) {
      const parts = rawRad.split('');
      parts.forEach(p => {
        if (!seenRadicals.has(p)) {
          seenRadicals.add(p);
          result.push({
            radical: p,
            meaning: RADICALS_DICT[p] || `${p} (Bộ thủ)`
          });
        }
      });
    }
  }

  // 3. Nếu vẫn hoàn toàn trống, bổ sung bộ thủ của các chữ cái đầu bằng cách thử tra cứu trực tiếp
  if (result.length === 0 && chars.length > 0) {
    chars.forEach(char => {
      // Tra cứu xem bản thân chữ này có nằm trong từ điển bộ thủ không
      if (RADICALS_DICT[char] && !seenRadicals.has(char)) {
        seenRadicals.add(char);
        result.push({
          radical: char,
          meaning: RADICALS_DICT[char]
        });
      }
    });
  }

  return result;
}
