// ============================================================
// VOCAB-BANK.JS — 1000 từ vựng tiếng Trung (dạng nén)
// Format: [id, char, pinyin, meaning, hsk, cat, strokes, exCn, exPy, exVi]
// HSK 1: 150 từ | HSK 2: 150 từ | HSK 3: 300 từ | HSK 4: 300 từ | HSK 5-6: 100 từ
// ============================================================

const _ = (id, c, p, m, h, cat, s, ex, ep, ev) => ({
  id, character: c, pinyin: p, meaning: m, hskLevel: h, category: cat,
  strokeCount: s, exampleSentence: ex, examplePinyin: ep, exampleVi: ev,
  breakdown: [], mnemonic: ''
});

// ─── HSK 1: id 74–220 (147 từ mới) ──────────────────────────
export const hsk1 = [
  _(74,'们','men','Chúng (hậu tố số nhiều)',1,'noun',5,'我们一起去。','Wǒmen yīqǐ qù.','Chúng ta cùng đi.'),
  _(75,'他','tā','Anh ấy',1,'pronoun',5,'他是老师。','Tā shì lǎoshī.','Anh ấy là giáo viên.'),
  _(76,'她','tā','Cô ấy',1,'pronoun',6,'她是学生。','Tā shì xuéshēng.','Cô ấy là học sinh.'),
  _(77,'它','tā','Nó',1,'pronoun',5,'它是一只猫。','Tā shì yī zhī māo.','Nó là một con mèo.'),
  _(78,'什么','shénme','Cái gì',1,'pronoun',8,'你叫什么？','Nǐ jiào shénme?','Bạn tên gì?'),
  _(79,'哪儿','nǎr','Đâu',1,'pronoun',11,'你去哪儿？','Nǐ qù nǎr?','Bạn đi đâu?'),
  _(80,'几','jǐ','Mấy',1,'adverb',2,'你有几本书？','Nǐ yǒu jǐ běn shū?','Bạn có mấy quyển sách?'),
  _(81,'多少','duōshǎo','Bao nhiêu',1,'adverb',12,'多少钱？','Duōshao qián?','Bao nhiêu tiền?'),
  _(82,'很','hěn','Rất',1,'adverb',9,'很好。','Hěn hǎo.','Rất tốt.'),
  _(83,'非常','fēicháng','Cực kỳ',1,'adverb',16,'非常好。','Fēicháng hǎo.','Cực kỳ tốt.'),
  _(84,'太','tài','Quá',1,'adverb',4,'太好了！','Tài hǎo le!','Tuyệt quá!'),
  _(85,'都','dōu','Đều',1,'adverb',10,'我们都是学生。','Wǒmen dōu shì xuéshēng.','Chúng tôi đều là học sinh.'),
  _(86,'和','hé','Và',1,'conjunction',8,'我和你。','Wǒ hé nǐ.','Tôi và bạn.'),
  _(87,'在','zài','Ở, Tại',1,'preposition',6,'我在学校。','Wǒ zài xuéxiào.','Tôi ở trường.'),
  _(88,'里','lǐ','Trong',1,'noun',7,'教室里。','Jiàoshì lǐ.','Trong lớp học.'),
  _(89,'上','shàng','Trên',1,'noun',3,'桌子上。','Zhuōzi shàng.','Trên bàn.'),
  _(90,'下','xià','Dưới',1,'noun',3,'椅子下。','Yǐzi xià.','Dưới ghế.'),
  _(91,'前','qián','Trước',1,'noun',9,'学校前。','Xuéxiào qián.','Trước trường.'),
  _(92,'后','hòu','Sau',1,'noun',6,'门后。','Mén hòu.','Sau cửa.'),
  _(93,'今天','jīntiān','Hôm nay',1,'noun',12,'今天星期一。','Jīntiān xīngqī yī.','Hôm nay thứ hai.'),
  _(94,'明天','míngtiān','Ngày mai',1,'noun',12,'明天见。','Míngtiān jiàn.','Ngày mai gặp.'),
  _(95,'昨天','zuótiān','Hôm qua',1,'noun',13,'昨天星期一。','Zuótiān xīngqī yī.','Hôm qua thứ hai.'),
  _(96,'早上','zǎoshang','Buổi sáng',1,'noun',14,'早上好。','Zǎoshang hǎo.','Chào buổi sáng.'),
  _(97,'中午','zhōngwǔ','Buổi trưa',1,'noun',11,'中午吃饭。','Zhōngwǔ chīfàn.','Ăn cơm trưa.'),
  _(98,'晚上','wǎnshang','Buổi tối',1,'noun',17,'晚上好。','Wǎnshang hǎo.','Chào buổi tối.'),
  _(99,'现在','xiànzài','Bây giờ',1,'adverb',15,'现在几点？','Xiànzài jǐ diǎn?','Bây giờ mấy giờ?'),
  _(100,'点','diǎn','Giờ',1,'noun',9,'八点。','Bā diǎn.','Tám giờ.'),
  _(101,'半','bàn','Rưỡi',1,'noun',5,'八点半。','Bā diǎn bàn.','Tám giờ rưỡi.'),
  _(102,'分','fēn','Phút',1,'noun',4,'八点十分。','Bā diǎn shí fēn.','Tám giờ mười phút.'),
  _(103,'月','yuè','Tháng',1,'noun',4,'五月。','Wǔ yuè.','Tháng năm.'),
  _(104,'年','nián','Năm',1,'noun',6,'二零二四年。','Èr líng èr sì nián.','Năm 2024.'),
  _(105,'号','hào','Ngày',1,'noun',5,'五月二十号。','Wǔ yuè èrshí hào.','Ngày 20 tháng 5.'),
  _(106,'星期','xīngqī','Tuần',1,'noun',14,'星期一。','Xīngqī yī.','Thứ hai.'),
  _(107,'爸爸','bàba','Bố',1,'noun',8,'我爸爸是医生。','Wǒ bàba shì yīshēng.','Bố tôi là bác sĩ.'),
  _(108,'妈妈','māma','Mẹ',1,'noun',10,'我妈妈很漂亮。','Wǒ māma hěn piàoliang.','Mẹ tôi rất đẹp.'),
  _(109,'哥哥','gēge','Anh trai',1,'noun',16,'我哥哥很高。','Wǒ gēge hěn gāo.','Anh trai tôi rất cao.'),
  _(110,'姐姐','jiějie','Chị gái',1,'noun',15,'我姐姐是老师。','Wǒ jiějie shì lǎoshī.','Chị tôi là giáo viên.'),
  _(111,'妹妹','mèimei','Em gái',1,'noun',11,'我妹妹十岁。','Wǒ mèimei shí suì.','Em gái tôi 10 tuổi.'),
  _(112,'弟弟','dìdi','Em trai',1,'noun',12,'我弟弟八岁。','Wǒ dìdi bā suì.','Em trai tôi 8 tuổi.'),
  _(113,'儿子','érzi','Con trai',1,'noun',11,'他有一个儿子。','Tā yǒu yī gè érzi.','Anh ấy có một con trai.'),
  _(114,'女儿','nǚ er','Con gái',1,'noun',9,'她有一个女儿。','Tā yǒu yī gè nǚ er.','Cô ấy có một con gái.'),
  _(115,'老师','lǎoshī','Giáo viên',1,'noun',16,'王老师很好。','Wáng lǎoshī hěn hǎo.','Cô giáo Vương rất tốt.'),
  _(116,'学生','xuéshēng','Học sinh',1,'noun',15,'我是学生。','Wǒ shì xuéshēng.','Tôi là học sinh.'),
  _(117,'朋友','péngyǒu','Bạn bè',1,'noun',12,'他是我的朋友。','Tā shì wǒ de péngyǒu.','Anh ấy là bạn tôi.'),
  _(118,'名字','míngzì','Tên',1,'noun',11,'你叫什么名字？','Nǐ jiào shénme míngzì?','Bạn tên gì?'),
  _(119,'学校','xuéxiào','Trường học',1,'noun',16,'我在学校学习。','Wǒ zài xuéxiào xuéxí.','Tôi học ở trường.'),
  _(120,'教室','jiàoshì','Lớp học',1,'noun',16,'教室很大。','Jiàoshì hěn dà.','Lớp học rất rộng.'),
  _(121,'书','shū','Sách',1,'noun',4,'一本书。','Yī běn shū.','Một quyển sách.'),
  _(122,'笔','bǐ','Bút',1,'noun',10,'一支笔。','Yī zhī bǐ.','Một cây bút.'),
  _(123,'桌子','zhuōzi','Bàn',1,'noun',14,'桌子上面有书。','Zhuōzi shàngmiàn yǒu shū.','Trên bàn có sách.'),
  _(124,'椅子','yǐzi','Ghế',1,'noun',16,'一把椅子。','Yī bǎ yǐzi.','Một cái ghế.'),
  _(125,'门','mén','Cửa',1,'noun',3,'开门。','Kāi mén.','Mở cửa.'),
  _(126,'窗','chuāng','Cửa sổ',1,'noun',12,'开窗。','Kāi chuāng.','Mở cửa sổ.'),
  _(127,'房间','fángjiān','Phòng',1,'noun',14,'我的房间。','Wǒ de fángjiān.','Phòng của tôi.'),
  _(128,'衣服','yīfu','Quần áo',1,'noun',12,'新衣服。','Xīn yīfu.','Quần áo mới.'),
  _(129,'鞋','xié','Giày',1,'noun',15,'一双鞋。','Yī shuāng xié.','Một đôi giày.'),
  _(130,'钱包','qiánbāo','Ví',1,'noun',15,'我的钱包。','Wǒ de qiánbāo.','Ví của tôi.'),
  _(131,'手机','shǒujī','Điện thoại',1,'noun',11,'我的手机。','Wǒ de shǒujī.','Điện thoại của tôi.'),
  _(132,'电脑','diànnǎo','Máy tính',1,'noun',10,'用电脑学习。','Yòng diànnǎo xuéxí.','Dùng máy tính học.'),
  _(133,'电视','diànshì','Tivi',1,'noun',13,'看电视。','Kàn diànshì.','Xem tivi.'),
  _(134,'水果','shuǐguǒ','Hoa quả',1,'noun',12,'我喜欢吃水果。','Wǒ xǐhuān chī shuǐguǒ.','Tôi thích ăn hoa quả.'),
  _(135,'苹果','píngguǒ','Táo',1,'noun',11,'一个苹果。','Yīgè píngguǒ.','Một quả táo.'),
  _(136,'鸡蛋','jīdàn','Trứng gà',1,'noun',13,'两个鸡蛋。','Liǎng gè jīdàn.','Hai quả trứng.'),
  _(137,'牛奶','niúnǎi','Sữa bò',1,'noun',9,'喝牛奶。','Hē niúnǎi.','Uống sữa.'),
  _(138,'面包','miànbāo','Bánh mì',1,'noun',16,'吃面包。','Chī miànbāo.','Ăn bánh mì.'),
  _(139,'米饭','mǐfàn','Cơm',1,'noun',13,'吃米饭。','Chī mǐfàn.','Ăn cơm.'),
  _(140,'面条','miàntiáo','Mì',1,'noun',19,'吃面条。','Chī miàntiáo.','Ăn mì.'),
  _(141,'茶','chá','Trà',1,'noun',9,'喝茶。','Hē chá.','Uống trà.'),
  _(142,'咖啡','kāfēi','Cà phê',1,'noun',11,'喝咖啡。','Hē kāfēi.','Uống cà phê.'),
  _(143,'可乐','kělè','Coca',1,'noun',11,'一瓶可乐。','Yī píng kělè.','Một chai coca.'),
  _(144,'医院','yīyuàn','Bệnh viện',1,'noun',15,'去医院。','Qù yīyuàn.','Đi bệnh viện.'),
  _(145,'商店','shāngdiàn','Cửa hàng',1,'noun',16,'去商店。','Qù shāngdiàn.','Đi cửa hàng.'),
  _(146,'银行','yínháng','Ngân hàng',1,'noun',13,'去银行。','Qù yínháng.','Đi ngân hàng.'),
  _(147,'公园','gōngyuán','Công viên',1,'noun',11,'去公园。','Qù gōngyuán.','Đi công viên.'),
  _(148,'饭店','fàndiàn','Nhà hàng',1,'noun',14,'去饭店吃饭。','Qù fàndiàn chīfàn.','Đi nhà hàng ăn.'),
  _(149,'图书馆','túshūguǎn','Thư viện',1,'noun',17,'去图书馆看书。','Qù túshūguǎn kànshū.','Đi thư viện đọc sách.'),
  _(150,'家','jiā','Nhà',1,'noun',10,'回家。','Huí jiā.','Về nhà.'),
  _(151,'宿舍','sùshè','Ký túc xá',1,'noun',15,'住宿舍。','Zhù sùshè.','Ở ký túc xá.'),
  _(152,'天气','tiānqì','Thời tiết',1,'noun',10,'天气很好。','Tiānqì hěn hǎo.','Thời tiết rất tốt.'),
  _(153,'雨','yǔ','Mưa',1,'noun',8,'下雨了。','Xià yǔ le.','Mưa rồi.'),
  _(154,'雪','xuě','Tuyết',1,'noun',11,'下雪了。','Xià xuě le.','Tuyết rồi.'),
  _(155,'冷','lěng','Lạnh',1,'adjective',7,'今天很冷。','Jīntiān hěn lěng.','Hôm nay lạnh.'),
  _(156,'热','rè','Nóng',1,'adjective',10,'今天很热。','Jīntiān hěn rè.','Hôm nay nóng.'),
  _(157,'高兴','gāoxìng','Vui vẻ',1,'adjective',16,'我很高兴。','Wǒ hěn gāoxìng.','Tôi rất vui.'),
  _(158,'快乐','kuàilè','Hạnh phúc',1,'adjective',15,'生日快乐！','Shēngrì kuàilè!','Chúc mừng sinh nhật!'),
  _(159,'漂亮','piàoliang','Đẹp',1,'adjective',20,'她真漂亮。','Tā zhēn piàoliang.','Cô ấy thật đẹp.'),
  _(160,'好看','hǎokàn','Đẹp mắt',1,'adjective',13,'这件衣服好看。','Zhè jiàn yīfu hǎokàn.','Bộ quần áo này đẹp.'),
  _(161,'好吃','hǎochī','Ngon',1,'adjective',13,'很好吃。','Hěn hǎochī.','Rất ngon.'),
  _(162,'忙','máng','Bận',1,'adjective',6,'我很忙。','Wǒ hěn máng.','Tôi rất bận.'),
  _(163,'高兴','gāoxìng','Vui',1,'adjective',16,'很高兴认识你。','Hěn gāoxìng rènshi nǐ.','Rất vui được biết bạn.'),
  _(164,'知道','zhīdao','Biết',1,'verb',13,'我知道。','Wǒ zhīdao.','Tôi biết.'),
  _(165,'认识','rènshi','Quen biết',1,'verb',11,'认识你很高兴。','Rènshi nǐ hěn gāoxìng.','Rất vui được biết bạn.'),
  _(166,'会说','huì shuō','Biết nói',1,'verb',15,'我会说中文。','Wǒ huì shuō Zhōngwén.','Tôi biết nói tiếng Trung.'),
  _(167,'想','xiǎng','Muốn, Nhớ',1,'verb',13,'我想回家。','Wǒ xiǎng huí jiā.','Tôi muốn về nhà.'),
  _(168,'要','yào','Muốn, Cần',1,'verb',9,'我要喝水。','Wǒ yào hē shuǐ.','Tôi muốn uống nước.'),
  _(169,'可以','kěyǐ','Có thể',1,'verb',9,'我可以进来吗？','Wǒ kěyǐ jìnlái ma?','Tôi có thể vào không?'),
  _(170,'能','néng','Có thể',1,'verb',10,'我能去。','Wǒ néng qù.','Tôi có thể đi.'),
  _(171,'喜欢','xǐhuān','Thích',1,'verb',15,'我喜欢猫。','Wǒ xǐhuān māo.','Tôi thích mèo.'),
  _(172,'爱','ài','Yêu',1,'verb',10,'我爱你。','Wǒ ài nǐ.','Anh yêu em.'),
  _(173,'觉得','juéde','Cảm thấy',1,'verb',16,'我觉得很好。','Wǒ juéde hěn hǎo.','Tôi cảm thấy rất tốt.'),
  _(174,'请','qǐng','Mời, Xin',1,'verb',10,'请进。','Qǐng jìn.','Mời vào.'),
  _(175,'对不起','duìbuqǐ','Xin lỗi',1,'verb',20,'对不起。','Duìbuqǐ.','Xin lỗi.'),
  _(176,'没关系','méiguānxi','Không sao',1,'verb',20,'没关系。','Méiguānxi.','Không sao.'),
  _(177,'谢谢','xièxie','Cảm ơn',1,'verb',18,'谢谢您。','Xièxie nín.','Cảm ơn ngài.'),
  _(178,'再见','zàijiàn','Tạm biệt',1,'verb',12,'明天见。','Míngtiān jiàn.','Hẹn gặp lại.'),
  _(179,'住','zhù','Ở',1,'verb',7,'我住在这里。','Wǒ zhù zài zhèlǐ.','Tôi ở đây.'),
  _(180,'工作','gōngzuò','Làm việc',1,'verb',5,'我在银行工作。','Wǒ zài yínháng gōngzuò.','Tôi làm việc ở ngân hàng.'),
  _(181,'学习','xuéxí','Học tập',1,'verb',13,'我学习中文。','Wǒ xuéxí Zhōngwén.','Tôi học tiếng Trung.'),
  _(182,'教','jiāo','Dạy',1,'verb',11,'我教英语。','Wǒ jiāo Yīngyǔ.','Tôi dạy tiếng Anh.'),
  _(183,'买','mǎi','Mua',1,'verb',6,'我买书。','Wǒ mǎi shū.','Tôi mua sách.'),
  _(184,'卖','mài','Bán',1,'verb',8,'他卖水果。','Tā mài shuǐguǒ.','Anh ấy bán hoa quả.'),
  _(185,'给','gěi','Cho',1,'verb',9,'给我。','Gěi wǒ.','Đưa cho tôi.'),
  _(186,'找','zhǎo','Tìm',1,'verb',7,'找人。','Zhǎo rén.','Tìm người.'),
  _(187,'等','děng','Đợi',1,'verb',12,'等我。','Děng wǒ.','Đợi tôi.'),
  _(188,'叫','jiào','Gọi, Tên là',1,'verb',5,'我叫小明。','Wǒ jiào Xiǎomíng.','Tôi tên là Tiểu Minh.'),
  _(189,'做','zuò','Làm',1,'verb',11,'做作业。','Zuò zuòyè.','Làm bài tập.'),
  _(190,'用','yòng','Dùng',1,'verb',5,'用笔写字。','Yòng bǐ xiězì.','Dùng bút viết chữ.'),
  _(191,'帮助','bāngzhù','Giúp đỡ',1,'verb',14,'请帮助我。','Qǐng bāngzhù wǒ.','Xin giúp tôi.'),
  _(192,'送','sòng','Tặng, Tiễn',1,'verb',9,'送你。','Sòng nǐ.','Tặng bạn.'),
  _(193,'让','ràng','Để cho',1,'verb',5,'让我看看。','Ràng wǒ kànkan.','Để tôi xem.'),
  _(194,'一起','yīqǐ','Cùng nhau',1,'adverb',10,'一起去。','Yīqǐ qù.','Cùng đi.'),
  _(195,'已经','yǐjīng','Đã',1,'adverb',9,'已经八点了。','Yǐjīng bā diǎn le.','Đã 8 giờ rồi.'),
  _(196,'还','hái','Vẫn còn',1,'adverb',7,'还在学习。','Hái zài xuéxí.','Vẫn đang học.'),
  _(197,'又','yòu','Lại',1,'adverb',2,'又来了。','Yòu lái le.','Lại đến rồi.'),
  _(198,'再','zài','Lần nữa',1,'adverb',6,'再说一遍。','Zài shuō yī biàn.','Nói lại một lần.'),
  _(199,'才','cái','Mới',1,'adverb',3,'才八点。','Cái bā diǎn.','Mới 8 giờ.'),
  _(200,'就','jiù','Thì, Liền',1,'adverb',12,'就去。','Jiù qù.','Liền đi.'),
  _(201,'最','zuì','Nhất',1,'adverb',12,'最好。','Zuì hǎo.','Tốt nhất.'),
  _(202,'真','zhēn','Thật',1,'adverb',10,'真好。','Zhēn hǎo.','Thật tốt.'),
  _(203,'对','duì','Đúng',1,'adjective',5,'对了。','Duì le.','Đúng rồi.'),
  _(204,'错','cuò','Sai',1,'adjective',13,'错了。','Cuò le.','Sai rồi.'),
  _(205,'多','duō','Nhiều',1,'adjective',6,'很多人。','Hěn duō rén.','Nhiều người.'),
  _(206,'少','shǎo','Ít',1,'adjective',4,'很少。','Hěn shǎo.','Rất ít.'),
  _(207,'快','kuài','Nhanh',1,'adjective',7,'太快了。','Tài kuài le.','Nhanh quá.'),
  _(208,'慢','màn','Chậm',1,'adjective',14,'请说慢一点。','Qǐng shuō màn yīdiǎn.','Xin nói chậm một chút.'),
  _(209,'远','yuǎn','Xa',1,'adjective',7,'很远。','Hěn yuǎn.','Rất xa.'),
  _(210,'近','jìn','Gần',1,'adjective',7,'很近。','Hěn jìn.','Rất gần.'),
  _(211,'新','xīn','Mới',1,'adjective',13,'新书。','Xīn shū.','Sách mới.'),
  _(212,'旧','jiù','Cũ',1,'adjective',5,'旧书。','Jiù shū.','Sách cũ.'),
  _(213,'贵','guì','Đắt',1,'adjective',9,'太贵了。','Tài guì le.','Đắt quá.'),
  _(214,'便宜','piányi','Rẻ',1,'adjective',15,'很便宜。','Hěn piányi.','Rất rẻ.'),
  _(215,'高','gāo','Cao',1,'adjective',10,'很高。','Hěn gāo.','Rất cao.'),
  _(216,'矮','ǎi','Thấp',1,'adjective',13,'很矮。','Hěn ǎi.','Rất thấp.'),
  _(217,'长','cháng','Dài',1,'adjective',4,'很长。','Hěn cháng.','Rất dài.'),
  _(218,'短','duǎn','Ngắn',1,'adjective',12,'很短。','Hěn duǎn.','Rất ngắn.'),
  _(219,'胖','pàng','Mập',1,'adjective',9,'很胖。','Hěn pàng.','Rất mập.'),
  _(220,'瘦','shòu','Ốm',1,'adjective',14,'很瘦。','Hěn shòu.','Rất ốm.'),
  // giao tiếp đời sống bổ sung
  _(1201,'出租车','chūzūchē','Taxi',1,'noun',28,'我坐出租车去公司。','Wǒ zuò chūzūchē qù gōngsī.','Tôi đi taxi đến công ty.'),
  _(1202,'地铁站','dìtiězhàn','Ga tàu điện ngầm',1,'noun',25,'地铁站在哪儿？','Dìtiězhàn zài nǎr?','Ga tàu điện ngầm ở đâu?'),
  _(1203,'菜单','càidān','Thực đơn',1,'noun',19,'请给我菜单。','Qǐng gěi wǒ càidān.','Cho tôi xin thực đơn.'),
  _(1204,'买单','mǎidān','Thanh toán',1,'verb',19,'服务员，买单。','Fúwùyuán, mǎidān.','Phục vụ ơi, tính tiền.'),
  _(1205,'服务员','fúwùyuán','Nhân viên phục vụ',1,'noun',22,'服务员很热情。','Fúwùyuán hěn rèqíng.','Nhân viên phục vụ rất nhiệt tình.'),
  _(1206,'上班','shàngbān','Đi làm',1,'verb',13,'我八点上班。','Wǒ bā diǎn shàngbān.','Tôi đi làm lúc 8 giờ.'),
  _(1207,'下班','xiàbān','Tan làm',1,'verb',10,'我六点下班。','Wǒ liù diǎn xiàbān.','Tôi tan làm lúc 6 giờ.'),
  _(1208,'同学','tóngxué','Bạn học',1,'noun',16,'我的同学会说中文。','Wǒ de tóngxué huì shuō Zhōngwén.','Bạn học của tôi biết nói tiếng Trung.'),
  _(1209,'邻居','línjū','Hàng xóm',1,'noun',22,'我的邻居很友好。','Wǒ de línjū hěn yǒuhǎo.','Hàng xóm của tôi rất thân thiện.'),
  _(1210,'排队','páiduì','Xếp hàng',1,'verb',17,'请排队。','Qǐng páiduì.','Xin vui lòng xếp hàng.'),
  _(1211,'快递','kuàidì','Chuyển phát nhanh',1,'noun',17,'我的快递到了。','Wǒ de kuàidì dào le.','Đơn chuyển phát của tôi đến rồi.'),
  _(1212,'地址','dìzhǐ','Địa chỉ',1,'noun',10,'请写地址。','Qǐng xiě dìzhǐ.','Xin hãy viết địa chỉ.'),
];

// ─── HSK 2: id 221–370 (150 từ mới) ─────────────────────────
export const hsk2 = [
  _(221,'比','bǐ','Hơn (so sánh)',2,'preposition',4,'我比你高。','Wǒ bǐ nǐ gāo.','Tôi cao hơn bạn.'),
  _(222,'比较','bǐjiào','Khá, Tương đối',2,'adverb',8,'比较好。','Bǐjiào hǎo.','Khá tốt.'),
  _(223,'已经','yǐjīng','Đã...rồi',2,'adverb',9,'已经十二点了。','Yǐjīng shí èr diǎn le.','Đã 12 giờ rồi.'),
  _(224,'因为','yīnwèi','Bởi vì',2,'conjunction',12,'因为下雨，所以不去。','Yīnwèi xià yǔ, suǒyǐ bù qù.','Vì mưa nên không đi.'),
  _(225,'所以','suǒyǐ','Cho nên',2,'conjunction',12,'因为忙，所以没去。','Yīnwèi máng, suǒyǐ méi qù.','Vì bận nên không đi.'),
  _(226,'但是','dànshì','Nhưng',2,'conjunction',13,'但是我不想去。','Dànshì wǒ bù xiǎng qù.','Nhưng tôi không muốn đi.'),
  _(227,'而且','érqiě','Hơn nữa',2,'conjunction',13,'而且很便宜。','Érqiě hěn piányi.','Hơn nữa rất rẻ.'),
  _(228,'虽然','suīrán','Mặc dù',2,'conjunction',14,'虽然贵，但是好吃。','Suīrán guì, dànshì hǎochī.','Mặc dù đắt nhưng ngon.'),
  _(229,'如果','rúguǒ','Nếu',2,'conjunction',11,'如果下雨，就不去。','Rúguǒ xià yǔ, jiù bù qù.','Nếu mưa thì không đi.'),
  _(230,'但是','dànshì','Nhưng',2,'conjunction',13,'但是很累。','Dànshì hěn lèi.','Nhưng rất mệt.'),
  _(231,'可以','kěyǐ','Có thể',2,'verb',9,'可以进来吗？','Kěyǐ jìnlái ma?','Có thể vào không?'),
  _(232,'应该','yīnggāi','Nên',2,'verb',15,'应该努力。','Yīnggāi nǔlì.','Nên cố gắng.'),
  _(233,'必须','bìxū','Phải',2,'verb',11,'必须去。','Bìxū qù.','Phải đi.'),
  _(234,'愿意','yuànyì','Bằng lòng',2,'verb',18,'我愿意。','Wǒ yuànyì.','Tôi bằng lòng.'),
  _(235,'可能','kěnéng','Có thể',2,'verb',13,'可能下雨。','Kěnéng xià yǔ.','Có thể mưa.'),
  _(236,'打算','dǎsuàn','Dự định',2,'verb',19,'打算去北京。','Dǎsuàn qù Běijīng.','Dự định đi Bắc Kinh.'),
  _(237,'开始','kāishǐ','Bắt đầu',2,'verb',12,'开始学习。','Kāishǐ xuéxí.','Bắt đầu học.'),
  _(238,'结束','jiéshù','Kết thúc',2,'verb',17,'结束了。','Jiéshù le.','Kết thúc rồi.'),
  _(239,'变成','biànchéng','Trở thành',2,'verb',15,'变成大人。','Biànchéng dà rén.','Trở thành người lớn.'),
  _(240,'改变','gǎibiàn','Thay đổi',2,'verb',13,'改变主意。','Gǎibiàn zhǔyi.','Thay đổi ý định.'),
  _(241,'告诉','gàosu','Nói cho',2,'verb',13,'告诉我。','Gàosu wǒ.','Nói cho tôi.'),
  _(242,'问','wèn','Hỏi',2,'verb',6,'问路。','Wèn lù.','Hỏi đường.'),
  _(243,'回答','huídá','Trả lời',2,'verb',12,'回答问题。','Huídá wèntí.','Trả lời câu hỏi.'),
  _(244,'介绍','jièshào','Giới thiệu',2,'verb',8,'介绍一下。','Jièshào yīxià.','Giới thiệu một chút.'),
  _(245,'参加','cānjiā','Tham gia',2,'verb',12,'参加比赛。','Cānjiā bǐsài.','Tham gia thi đấu.'),
  _(246,'运动','yùndòng','Vận động',2,'verb',16,'做运动。','Zuò yùndòng.','Tập thể dục.'),
  _(247,'跑步','pǎobù','Chạy bộ',2,'verb',16,'每天跑步。','Měitiān pǎobù.','Chạy bộ mỗi ngày.'),
  _(248,'游泳','yóuyǒng','Bơi',2,'verb',16,'喜欢游泳。','Xǐhuān yóuyǒng.','Thích bơi.'),
  _(249,'旅游','lǚyóu','Du lịch',2,'verb',16,'去旅游。','Qù lǚyóu.','Đi du lịch.'),
  _(250,'唱歌','chànggē','Hát',2,'verb',18,'喜欢唱歌。','Xǐhuān chànggē.','Thích hát.'),
  _(251,'跳舞','tiàowǔ','Nhảy múa',2,'verb',20,'会跳舞。','Huì tiàowǔ.','Biết nhảy.'),
  _(252,'画画','huà huà','Vẽ',2,'verb',16,'喜欢画画。','Xǐhuān huà huà.','Thích vẽ.'),
  _(253,'做饭','zuòfàn','Nấu cơm',2,'verb',14,'妈妈做饭。','Māma zuòfàn.','Mẹ nấu cơm.'),
  _(254,'洗澡','xǐzǎo','Tắm',2,'verb',15,'去洗澡。','Qù xǐzǎo.','Đi tắm.'),
  _(255,'起床','qǐchuáng','Thức dậy',2,'verb',17,'七点起床。','Qī diǎn qǐchuáng.','Thức dậy lúc 7 giờ.'),
  _(256,'睡觉','shuìjiào','Ngủ',2,'verb',18,'十点睡觉。','Shí diǎn shuìjiào.','Ngủ lúc 10 giờ.'),
  _(257,'休息','xiūxi','Nghỉ ngơi',2,'verb',12,'休息一下。','Xiūxi yīxià.','Nghỉ ngơi một chút.'),
  _(258,'生病','shēngbìng','Bị ốm',2,'verb',12,'生病了。','Shēngbìng le.','Bị ốm rồi.'),
  _(259,'担心','dānxīn','Lo lắng',2,'verb',12,'别担心。','Bié dānxīn.','Đừng lo.'),
  _(260,'放心','fàngxīn','Yên tâm',2,'verb',12,'请放心。','Qǐng fàngxīn.','Xin yên tâm.'),
  _(261,'小心','xiǎoxīn','Cẩn thận',2,'adjective',9,'小心点。','Xiǎoxīn diǎn.','Cẩn thận một chút.'),
  _(262,'着急','zháojí','Sốt ruột',2,'adjective',16,'别着急。','Bié zháojí.','Đừng sốt ruột.'),
  _(263,'安静','ānjìng','Yên tĩnh',2,'adjective',12,'请安静。','Qǐng ānjìng.','Xin hãy yên lặng.'),
  _(264,'重要','zhòngyào','Quan trọng',2,'adjective',14,'很重要。','Hěn zhòngyào.','Rất quan trọng.'),
  _(265,'简单','jiǎndān','Đơn giản',2,'adjective',18,'很简单。','Hěn jiǎndān.','Rất đơn giản.'),
  _(266,'容易','róngyì','Dễ dàng',2,'adjective',14,'很容易。','Hěn róngyì.','Rất dễ dàng.'),
  _(267,'难','nán','Khó',2,'adjective',10,'很难。','Hěn nán.','Rất khó.'),
  _(268,'累','lèi','Mệt',2,'adjective',11,'很累。','Hěn lèi.','Rất mệt.'),
  _(269,'饱','bǎo','No',2,'adjective',8,'吃饱了。','Chī bǎo le.','Ăn no rồi.'),
  _(270,'渴','kě','Khát',2,'adjective',12,'我渴了。','Wǒ kě le.','Tôi khát rồi.'),
  _(271,'清楚','qīngchu','Rõ ràng',2,'adjective',17,'很清楚。','Hěn qīngchu.','Rất rõ ràng.'),
  _(272,'安全','ānquán','An toàn',2,'adjective',12,'注意安全。','Zhùyì ānquán.','Chú ý an toàn.'),
  _(273,'幸福','xìngfú','Hạnh phúc',2,'adjective',15,'很幸福。','Hěn xìngfú.','Rất hạnh phúc.'),
  _(274,'健康','jiànkāng','Khỏe mạnh',2,'adjective',15,'身体健康。','Shēntǐ jiànkāng.','Sức khỏe tốt.'),
  _(275,'特别','tèbié','Đặc biệt',2,'adverb',14,'特别好。','Tèbié hǎo.','Đặc biệt tốt.'),
  _(276,'一共','yīgòng','Tổng cộng',2,'adverb',10,'一共多少钱？','Yīgòng duōshao qián?','Tổng cộng bao nhiêu tiền?'),
  _(277,'一直','yīzhí','Mãi, Luôn',2,'adverb',12,'一直走。','Yīzhí zǒu.','Cứ đi thẳng.'),
  _(278,'一起','yīqǐ','Cùng nhau',2,'adverb',10,'一起吃饭。','Yīqǐ chīfàn.','Cùng ăn cơm.'),
  _(279,'马上','mǎshàng','Ngay lập tức',2,'adverb',9,'马上来。','Mǎshàng lái.','Đến ngay.'),
  _(280,'块','kuài','Đồng (tiền)',2,'measure_word',7,'十块钱。','Shí kuài qián.','Mười đồng.'),
  _(281,'岁','suì','Tuổi',2,'measure_word',6,'十岁。','Shí suì.','Mười tuổi.'),
  _(282,'次','cì','Lần',2,'measure_word',6,'一次。','Yī cì.','Một lần.'),
  _(283,'遍','biàn','Lần (đọc, nói)',2,'measure_word',12,'说一遍。','Shuō yī biàn.','Nói một lần.'),
  _(284,'条','tiáo','Cái (vật dài)',2,'measure_word',7,'一条鱼。','Yī tiáo yú.','Một con cá.'),
  _(285,'件','jiàn','Cái (quần áo)',2,'measure_word',6,'一件衣服。','Yī jiàn yīfu.','Một bộ quần áo.'),
  _(286,'双','shuāng','Đôi',2,'measure_word',4,'一双鞋。','Yī shuāng xié.','Một đôi giày.'),
  _(287,'杯','bēi','Cốc',2,'measure_word',8,'一杯水。','Yī bēi shuǐ.','Một cốc nước.'),
  _(288,'瓶','píng','Chai',2,'measure_word',10,'一瓶水。','Yī píng shuǐ.','Một chai nước.'),
  _(289,'碗','wǎn','Bát',2,'measure_word',13,'一碗饭。','Yī wǎn fàn.','Một bát cơm.'),
  _(290,'盘','pán','Đĩa',2,'measure_word',11,'一盘菜。','Yī pán cài.','Một đĩa thức ăn.'),
  _(291,'之前','zhīqián','Trước khi',2,'preposition',12,'之前说过。','Zhīqián shuō guo.','Đã nói trước đó.'),
  _(292,'之后','zhīhòu','Sau khi',2,'preposition',12,'之后再说。','Zhīhòu zài shuō.','Sau đó nói sau.'),
  _(293,'中间','zhōngjiān','Ở giữa',2,'noun',10,'中间有桌子。','Zhōngjiān yǒu zhuōzi.','Ở giữa có cái bàn.'),
  _(294,'旁边','pángbiān','Bên cạnh',2,'noun',16,'旁边有椅子。','Pángbiān yǒu yǐzi.','Bên cạnh có ghế.'),
  _(295,'对面','duìmiàn','Đối diện',2,'noun',13,'对面是银行。','Duìmiàn shì yínháng.','Đối diện là ngân hàng.'),
  _(296,'附近','fùjìn','Gần đây',2,'noun',12,'附近有商店。','Fùjìn yǒu shāngdiàn.','Gần đây có cửa hàng.'),
  _(297,'外面','wàimiàn','Bên ngoài',2,'noun',11,'在外面等。','Zài wàimiàn děng.','Đợi ở ngoài.'),
  _(298,'里面','lǐmiàn','Bên trong',2,'noun',12,'在里面。','Zài lǐmiàn.','Ở bên trong.'),
  _(299,'一会儿','yīhuìr','Một lát',2,'adverb',10,'等一会儿。','Děng yīhuìr.','Đợi một lát.'),
  _(300,'刚才','gāngcái','Vừa nãy',2,'adverb',11,'刚才说的。','Gāngcái shuō de.','Vừa nãy nói.'),
  _(301,'经常','jīngcháng','Thường xuyên',2,'adverb',15,'经常去。','Jīngcháng qù.','Thường xuyên đi.'),
  _(302,'有时候','yǒu shíhou','Thỉnh thoảng',2,'adverb',16,'有时候去。','Yǒu shíhou qù.','Thỉnh thoảng đi.'),
  _(303,'从来不','cónglái bù','Chưa bao giờ',2,'adverb',18,'从来不抽烟。','Cónglái bù chōuyān.','Chưa bao giờ hút thuốc.'),
  _(304,'突然','tūrán','Đột nhiên',2,'adverb',15,'突然下雨了。','Tūrán xià yǔ le.','Đột nhiên mưa.'),
  _(305,'必须','bìxū','Phải',2,'adverb',11,'必须努力。','Bìxū nǔlì.','Phải cố gắng.'),
  _(306,'可能','kěnéng','Có thể',2,'adverb',13,'可能来。','Kěnéng lái.','Có thể đến.'),
  _(307,'方便','fāngbiàn','Tiện lợi',2,'adjective',13,'很方便。','Hěn fāngbiàn.','Rất tiện lợi.'),
  _(308,'合适','héshì','Phù hợp',2,'adjective',14,'很合适。','Hěn héshì.','Rất phù hợp.'),
  _(309,'热闹','rènào','Nhộn nhịp',2,'adjective',15,'很热闹。','Hěn rènào.','Rất nhộn nhịp.'),
  _(310,'挤','jǐ','Đông đúc',2,'adjective',9,'太挤了。','Tài jǐ le.','Đông quá.'),
  _(311,'脏','zāng','Bẩn',2,'adjective',10,'太脏了。','Tài zāng le.','Bẩn quá.'),
  _(312,'整齐','zhěngqí','Ngăn nắp',2,'adjective',20,'很整齐。','Hěn zhěngqí.','Rất ngăn nắp.'),
  _(313,'年轻','niánqīng','Trẻ',2,'adjective',12,'很年轻。','Hěn niánqīng.','Rất trẻ.'),
  _(314,'老','lǎo','Già',2,'adjective',6,'老了。','Lǎo le.','Già rồi.'),
  _(315,'嘴','zuǐ','Miệng',2,'noun',14,'张嘴。','Zhāng zuǐ.','Mở miệng.'),
  _(316,'耳朵','ěrduo','Tai',2,'noun',15,'大耳朵。','Dà ěrduo.','Tai to.'),
  _(317,'眼睛','yǎnjīng','Mắt',2,'noun',17,'大眼睛。','Dà yǎnjīng.','Mắt to.'),
  _(318,'鼻子','bízi','Mũi',2,'noun',15,'高鼻子。','Gāo bízi.','Mũi cao.'),
  _(319,'头发','tóufa','Tóc',2,'noun',15,'长头发。','Cháng tóufa.','Tóc dài.'),
  _(320,'脸','liǎn','Mặt',2,'noun',11,'洗脸。','Xǐ liǎn.','Rửa mặt.'),
  _(321,'头','tóu','Đầu',2,'noun',5,'头疼。','Tóu téng.','Đau đầu.'),
  _(322,'脚','jiǎo','Chân',2,'noun',11,'洗脚。','Xǐ jiǎo.','Rửa chân.'),
  _(323,'手','shǒu','Tay',2,'noun',4,'洗手。','Xǐ shǒu.','Rửa tay.'),
  _(324,'腿','tuǐ','Đùi, Chân',2,'noun',15,'腿疼。','Tuǐ téng.','Đau chân.'),
  _(325,'肚子','dùzi','Bụng',2,'noun',12,'肚子疼。','Dùzi téng.','Đau bụng.'),
  _(326,'牙','yá','Răng',2,'noun',4,'刷牙。','Shuā yá.','Đánh răng.'),
  _(327,'感冒','gǎnmào','Cảm cúm',2,'noun',19,'感冒了。','Gǎnmào le.','Bị cảm rồi.'),
  _(328,'发烧','fāshāo','Sốt',2,'verb',15,'发烧了。','Fāshāo le.','Bị sốt rồi.'),
  _(329,'咳嗽','késou','Ho',2,'verb',17,'咳嗽了。','Késou le.','Bị ho rồi.'),
  _(330,'药','yào','Thuốc',2,'noun',9,'吃药。','Chī yào.','Uống thuốc.'),
  _(331,'医院','yīyuàn','Bệnh viện',2,'noun',15,'去医院。','Qù yīyuàn.','Đi bệnh viện.'),
  _(332,'火车站','huǒchēzhàn','Ga tàu hỏa',2,'noun',17,'去火车站。','Qù huǒchēzhàn.','Đi ga tàu.'),
  _(333,'公共汽车','gōnggòng qìchē','Xe buýt',2,'noun',16,'坐公共汽车。','Zuò gōnggòng qìchē.','Đi xe buýt.'),
  _(334,'地铁','dìtiě','Tàu điện ngầm',2,'noun',10,'坐地铁。','Zuò dìtiě.','Đi tàu điện ngầm.'),
  _(335,'飞机','fēijī','Máy bay',2,'noun',10,'坐飞机。','Zuò fēijī.','Đi máy bay.'),
  _(336,'船','chuán','Tàu thủy',2,'noun',11,'坐船。','Zuò chuán.','Đi tàu.'),
  _(337,'自行车','zìxíngchē','Xe đạp',2,'noun',20,'骑自行车。','Qí zìxíngchē.','Đi xe đạp.'),
  _(338,'开车','kāichē','Lái xe',2,'verb',12,'开车去。','Kāichē qù.','Lái xe đi.'),
  _(339,'司机','sījī','Tài xế',2,'noun',11,'司机开车。','Sījī kāichē.','Tài xế lái xe.'),
  _(340,'马路','mǎlù','Đường phố',2,'noun',12,'过马路。','Guò mǎlù.','Qua đường.'),
  _(341,'红绿灯','hónglǜdēng','Đèn giao thông',2,'noun',20,'看红绿灯。','Kàn hónglǜdēng.','Nhìn đèn giao thông.'),
  _(342,'考试','kǎoshì','Thi',2,'noun',15,'考试了。','Kǎoshì le.','Thi rồi.'),
  _(343,'作业','zuòyè','Bài tập',2,'noun',14,'做作业。','Zuò zuòyè.','Làm bài tập.'),
  _(344,'放假','fàngjià','Nghỉ lễ',2,'verb',14,'放假了。','Fàngjià le.','Nghỉ lễ rồi.'),
  _(345,'放假','fàngjià','Nghỉ',2,'verb',14,'什么时候放假？','Shénme shíhou fàngjià?','Khi nào nghỉ?'),
  _(346,'假期','jiàqī','Kỳ nghỉ',2,'noun',15,'假期快乐。','Jiàqī kuàilè.','Kỳ nghỉ vui vẻ.'),
  _(347,'节日','jiérì','Ngày lễ',2,'noun',10,'节日快乐。','Jiérì kuàilè.','Chúc mừng ngày lễ.'),
  _(348,'春节','Chūnjié','Tết Nguyên đán',2,'noun',13,'春节快乐。','Chūnjié kuàilè.','Chúc mừng năm mới.'),
  _(349,'生日','shēngrì','Sinh nhật',2,'noun',12,'生日快乐。','Shēngrì kuàilè.','Chúc mừng sinh nhật.'),
  _(350,'礼物','lǐwù','Quà tặng',2,'noun',11,'送礼物。','Sòng lǐwù.','Tặng quà.'),
  _(351,'蛋糕','dàngāo','Bánh kem',2,'noun',16,'吃蛋糕。','Chī dàngāo.','Ăn bánh kem.'),
  _(352,'唱歌','chànggē','Hát',2,'verb',20,'一起唱歌。','Yīqǐ chànggē.','Cùng hát.'),
  _(353,'跳舞','tiàowǔ','Nhảy',2,'verb',20,'喜欢跳舞。','Xǐhuān tiàowǔ.','Thích nhảy.'),
  _(354,'踢足球','tī zúqiú','Đá bóng',2,'verb',18,'喜欢踢足球。','Xǐhuān tī zúqiú.','Thích đá bóng.'),
  _(355,'打篮球','dǎ lánqiú','Chơi bóng rổ',2,'verb',20,'打篮球。','Dǎ lánqiú.','Chơi bóng rổ.'),
  _(356,'乒乓球','pīngpāngqiú','Bóng bàn',2,'noun',18,'打乒乓球。','Dǎ pīngpāngqiú.','Chơi bóng bàn.'),
  _(357,'旅游','lǚyóu','Du lịch',2,'verb',16,'去旅游。','Qù lǚyóu.','Đi du lịch.'),
  _(358,'地图','dìtú','Bản đồ',2,'noun',10,'看地图。','Kàn dìtú.','Xem bản đồ.'),
  _(359,'火车','huǒchē','Tàu hỏa',2,'noun',10,'坐火车。','Zuò huǒchē.','Đi tàu hỏa.'),
  _(360,'汽车','qìchē','Ô tô',2,'noun',11,'开汽车。','Kāi qìchē.','Lái ô tô.'),
  _(361,'运动会','yùndònghuì','Hội thao',2,'noun',19,'参加运动会。','Cānjiā yùndònghuì.','Tham gia hội thao.'),
  _(362,'游戏','yóuxì','Trò chơi',2,'noun',19,'玩游戏。','Wán yóuxì.','Chơi game.'),
  _(363,'上网','shàngwǎng','Lên mạng',2,'verb',11,'上网学习。','Shàngwǎng xuéxí.','Lên mạng học.'),
  _(364,'聊天','liáotiān','Trò chuyện',2,'verb',21,'网上聊天。','Wǎngshàng liáotiān.','Trò chuyện online.'),
  _(365,'零钱','língqián','Tiền lẻ',2,'noun',16,'有零钱吗？','Yǒu língqián ma?','Có tiền lẻ không?'),
  _(366,'信用卡','xìnyòngkǎ','Thẻ tín dụng',2,'noun',17,'用信用卡付。','Yòng xìnyòngkǎ fù.','Trả bằng thẻ tín dụng.'),
  _(367,'阿姨','āyí','Dì, Cô',2,'noun',12,'阿姨好。','āyí hǎo.','Chào cô.'),
  _(368,'叔叔','shūshu','Chú',2,'noun',14,'叔叔好。','Shūshu hǎo.','Chào chú.'),
  _(369,'小姐','xiǎojiě','Cô (tiểu thư)',2,'noun',11,'小姐请。','Xiǎojiě qǐng.','Mời cô.'),
  _(370,'先生','xiānsheng','Ông, Anh',2,'noun',11,'先生您好。','Xiānsheng nín hǎo.','Xin chào ông.'),
  // giao tiếp đời sống bổ sung
  _(1301,'预约','yùyuē','Đặt lịch hẹn',2,'verb',17,'我想预约明天下午。','Wǒ xiǎng yùyuē míngtiān xiàwǔ.','Tôi muốn đặt lịch chiều mai.'),
  _(1302,'改天','gǎitiān','Để hôm khác',2,'adverb',11,'我们改天再见吧。','Wǒmen gǎitiān zài jiàn ba.','Chúng ta hẹn hôm khác gặp nhé.'),
  _(1303,'堵车','dǔchē','Kẹt xe',2,'verb',15,'今天早上堵车。','Jīntiān zǎoshang dǔchē.','Sáng nay bị kẹt xe.'),
  _(1304,'刷卡','shuākǎ','Quẹt thẻ',2,'verb',16,'可以刷卡吗？','Kěyǐ shuākǎ ma?','Có thể quẹt thẻ không?'),
  _(1305,'打包','dǎbāo','Gói mang về',2,'verb',8,'这个可以打包吗？','Zhège kěyǐ dǎbāo ma?','Món này có thể gói mang về không?'),
  _(1306,'口味','kǒuwèi','Khẩu vị',2,'noun',11,'这个口味太辣了。','Zhège kǒuwèi tài là le.','Khẩu vị này cay quá.'),
  _(1307,'前台','qiántái','Quầy lễ tân',2,'noun',13,'请到前台登记。','Qǐng dào qiántái dēngjì.','Xin tới quầy lễ tân đăng ký.'),
  _(1308,'登记','dēngjì','Đăng ký',2,'verb',17,'先登记再进去。','Xiān dēngjì zài jìnqù.','Đăng ký trước rồi vào.'),
  _(1309,'同事','tóngshì','Đồng nghiệp',2,'noun',10,'我的同事很专业。','Wǒ de tóngshì hěn zhuānyè.','Đồng nghiệp của tôi rất chuyên nghiệp.'),
  _(1310,'老板','lǎobǎn','Sếp, ông chủ',2,'noun',11,'老板今天不在。','Lǎobǎn jīntiān bú zài.','Hôm nay sếp không ở đây.'),
  _(1311,'回复','huífù','Phản hồi',2,'verb',12,'请尽快回复我。','Qǐng jǐnkuài huífù wǒ.','Xin phản hồi tôi sớm.'),
  _(1312,'消息','xiāoxi','Tin nhắn, tin tức',2,'noun',13,'我刚看到你的消息。','Wǒ gāng kàndào nǐ de xiāoxi.','Tôi vừa thấy tin nhắn của bạn.'),
];

// ─── HSK 3: id 371–670 (300 từ mới) ─────────────────────────
export const hsk3 = [
  _(371,'真的','zhēnde','Thật sự',3,'adverb',16,'真的吗？','Zhēn de ma?','Thật không?'),
  _(372,'其实','qíshí','Thực ra',3,'adverb',12,'其实我不知道。','Qíshí wǒ bù zhīdao.','Thực ra tôi không biết.'),
  _(373,'一直','yīzhí','Mãi, Luôn',3,'adverb',12,'一直等你。','Yīzhí děng nǐ.','Luôn đợi bạn.'),
  _(374,'总是','zǒngshì','Luôn luôn',3,'adverb',14,'总是迟到。','Zǒngshì chídào.','Luôn đến muộn.'),
  _(375,'从来','cónglái','Từ trước đến nay',3,'adverb',14,'从来不吃肉。','Cónglái bù chī ròu.','Xưa nay không ăn thịt.'),
  _(376,'正在','zhèngzài','Đang',3,'adverb',11,'正在学习。','Zhèngzài xuéxí.','Đang học.'),
  _(377,'已经','yǐjīng','Đã',3,'adverb',9,'已经完了。','Yǐjīng wán le.','Đã xong rồi.'),
  _(378,'终于','zhōngyú','Cuối cùng',3,'adverb',12,'终于到了。','Zhōngyú dào le.','Cuối cùng đã đến.'),
  _(379,'大概','dàgài','Đại khái',3,'adverb',11,'大概十点。','Dàgài shí diǎn.','Khoảng 10 giờ.'),
  _(380,'几乎','jīhū','Suýt, Hầu như',3,'adverb',8,'几乎忘了。','Jīhū wàng le.','Suýt quên.'),
  _(381,'其实','qíshí','Thực ra',3,'adverb',12,'其实不难。','Qíshí bù nán.','Thực ra không khó.'),
  _(382,'当然','dāngrán','Đương nhiên',3,'adverb',12,'当然可以。','Dāngrán kěyǐ.','Đương nhiên có thể.'),
  _(383,'不过','bùguò','Chỉ là, Nhưng',3,'conjunction',10,'不过太贵了。','Bùguò tài guì le.','Nhưng quá đắt.'),
  _(384,'而且','érqiě','Hơn nữa',3,'conjunction',13,'而且很好吃。','Érqiě hěn hǎochī.','Hơn nữa rất ngon.'),
  _(385,'或者','huòzhě','Hoặc',3,'conjunction',14,'或者你去。','Huòzhě nǐ qù.','Hoặc bạn đi.'),
  _(386,'还是','háishì','Hay vẫn',3,'conjunction',14,'你去还是我去？','Nǐ qù háishì wǒ qù?','Bạn đi hay tôi đi?'),
  _(387,'除了','chúle','Ngoại trừ',3,'preposition',14,'除了你，还有他。','Chúle nǐ, hái yǒu tā.','Ngoài bạn ra còn có anh ấy.'),
  _(388,'根据','gēnjù','Căn cứ vào',3,'preposition',16,'根据规定。','Gēnjù guīdìng.','Căn cứ quy định.'),
  _(389,'关于','guānyú','Về (liên quan)',3,'preposition',16,'关于学习。','Guānyú xuéxí.','Về việc học.'),
  _(390,'对于','duìyú','Đối với',3,'preposition',18,'对于我来说。','Duìyú wǒ lái shuō.','Đối với tôi mà nói.'),
  _(391,'当','dāng','Khi',3,'preposition',8,'当我学习时。','Dāng wǒ xuéxí shí.','Khi tôi học.'),
  _(392,'为了','wèile','Để, Vì',3,'preposition',11,'为了学习中文。','Wèile xuéxí Zhōngwén.','Để học tiếng Trung.'),
  _(393,'从','cóng','Từ',3,'preposition',12,'从北京来。','Cóng Běijīng lái.','Đến từ Bắc Kinh.'),
  _(394,'往','wǎng','Hướng về',3,'preposition',10,'往前走。','Wǎng qián zǒu.','Đi về phía trước.'),
  _(395,'向','xiàng','Hướng về',3,'preposition',7,'向左边。','Xiàng zuǒbiān.','Về bên trái.'),
  _(396,'对','duì','Đối với',3,'preposition',5,'对我好。','Duì wǒ hǎo.','Tốt với tôi.'),
  _(397,'把','bǎ','Đem (cấu trúc 把)',3,'preposition',7,'把书拿来。','Bǎ shū ná lái.','Đem sách lại đây.'),
  _(398,'被','bèi','Bị (bị động)',3,'preposition',10,'被打了。','Bèi dǎ le.','Bị đánh.'),
  _(399,'让','ràng','Để cho',3,'preposition',5,'让我去。','Ràng wǒ qù.','Để tôi đi.'),
  _(400,'叫','jiào','Bảo',3,'preposition',5,'叫他来。','Jiào tā lái.','Bảo anh ấy đến.'),
  _(401,'给','gěi','Cho',3,'preposition',9,'给我打电话。','Gěi wǒ dǎ diànhuà.','Gọi điện cho tôi.'),
  _(402,'和','hé','Với',3,'preposition',8,'和你一起去。','Hé nǐ yīqǐ qù.','Đi cùng với bạn.'),
  _(403,'跟','gēn','Theo, Với',3,'preposition',16,'跟我来。','Gēn wǒ lái.','Theo tôi.'),
  _(404,'比','bǐ','Hơn',3,'preposition',4,'比我好。','Bǐ wǒ hǎo.','Tốt hơn tôi.'),
  _(405,'像','xiàng','Giống như',3,'preposition',13,'像妈妈。','Xiàng māma.','Giống mẹ.'),
  _(406,'变成','biànchéng','Trở thành',3,'verb',15,'变成朋友。','Biànchéng péngyǒu.','Trở thành bạn bè.'),
  _(407,'成为','chéngwéi','Trở thành',3,'verb',12,'成为老师。','Chéngwéi lǎoshī.','Trở thành giáo viên.'),
  _(408,'觉得','juéde','Cảm thấy',3,'verb',16,'觉得很好。','Juéde hěn hǎo.','Cảm thấy rất tốt.'),
  _(409,'以为','yǐwéi','Tưởng rằng',3,'verb',9,'以为你不知道。','Yǐwéi nǐ bù zhīdao.','Tưởng bạn không biết.'),
  _(410,'相信','xiāngxìn','Tin tưởng',3,'verb',14,'我相信你。','Wǒ xiāngxìn nǐ.','Tôi tin bạn.'),
  _(411,'明白','míngbai','Hiểu',3,'verb',12,'明白了。','Míngbai le.','Hiểu rồi.'),
  _(412,'忘记','wàngjì','Quên',3,'verb',11,'忘记了。','Wàngjì le.','Quên rồi.'),
  _(413,'记得','jìde','Nhớ',3,'verb',14,'记得吗？','Jìde ma?','Nhớ không?'),
  _(414,'打算','dǎsuàn','Dự định',3,'verb',19,'打算去中国。','Dǎsuàn qù Zhōngguó.','Dự định đi Trung Quốc.'),
  _(415,'准备','zhǔnbèi','Chuẩn bị',3,'verb',17,'准备好了。','Zhǔnbèi hǎo le.','Chuẩn bị xong rồi.'),
  _(416,'决定','juédìng','Quyết định',3,'verb',12,'决定了。','Juédìng le.','Quyết định rồi.'),
  _(417,'同意','tóngyì','Đồng ý',3,'verb',12,'我同意。','Wǒ tóngyì.','Tôi đồng ý.'),
  _(418,'反对','fǎnduì','Phản đối',3,'verb',11,'我反对。','Wǒ fǎnduì.','Tôi phản đối.'),
  _(419,'讨论','tǎolùn','Thảo luận',3,'verb',13,'讨论问题。','Tǎolùn wèntí.','Thảo luận vấn đề.'),
  _(420,'建议','jiànyì','Đề nghị',3,'verb',14,'建议你去。','Jiànyì nǐ qù.','Đề nghị bạn đi.'),
  _(421,'表示','biǎoshì','Biểu thị',3,'verb',13,'表示同意。','Biǎoshì tóngyì.','Biểu thị đồng ý.'),
  _(422,'出现','chūxiàn','Xuất hiện',3,'verb',11,'出现了。','Chūxiàn le.','Xuất hiện rồi.'),
  _(423,'发生','fāshēng','Xảy ra',3,'verb',12,'发生了。','Fāshēng le.','Xảy ra rồi.'),
  _(424,'发现','fāxiàn','Phát hiện',3,'verb',12,'发现了。','Fāxiàn le.','Phát hiện ra rồi.'),
  _(425,'提高','tígāo','Nâng cao',3,'verb',17,'提高水平。','Tígāo shuǐpíng.','Nâng cao trình độ.'),
  _(426,'发展','fāzhǎn','Phát triển',3,'verb',13,'发展很快。','Fāzhǎn hěn kuài.','Phát triển rất nhanh.'),
  _(427,'变化','biànhuà','Biến hóa',3,'verb',14,'变化很大。','Biànhuà hěn dà.','Thay đổi rất lớn.'),
  _(428,'继续','jìxù','Tiếp tục',3,'verb',16,'继续学习。','Jìxù xuéxí.','Tiếp tục học.'),
  _(429,'坚持','jiānchí','Kiên trì',3,'verb',15,'坚持学习。','Jiānchí xuéxí.','Kiên trì học.'),
  _(430,'完成','wánchéng','Hoàn thành',3,'verb',12,'完成了。','Wánchéng le.','Hoàn thành rồi.'),
  _(431,'成功','chénggōng','Thành công',3,'verb',12,'成功了。','Chénggōng le.','Thành công rồi.'),
  _(432,'失败','shībài','Thất bại',3,'verb',11,'失败了。','Shībài le.','Thất bại rồi.'),
  _(433,'努力','nǔlì','Cố gắng',3,'adjective',13,'努力学习。','Nǔlì xuéxí.','Cố gắng học.'),
  _(434,'认真','rènzhēn','Nghiêm túc',3,'adjective',14,'认真学习。','Rènzhēn xuéxí.','Nghiêm túc học tập.'),
  _(435,'仔细','zǐxì','Cẩn thận, Kỹ',3,'adjective',15,'仔细看。','Zǐxì kàn.','Xem kỹ.'),
  _(436,'主动','zhǔdòng','Chủ động',3,'adjective',12,'主动学习。','Zhǔdòng xuéxí.','Chủ động học tập.'),
  _(437,'顺利','shùnlì','Suôn sẻ',3,'adjective',15,'一切顺利。','Yīqiè shùnlì.','Mọi việc suôn sẻ.'),
  _(438,'直接','zhíjiē','Trực tiếp',3,'adjective',14,'直接说。','Zhíjiē shuō.','Nói trực tiếp.'),
  _(439,'完全','wánquán','Hoàn toàn',3,'adverb',13,'完全不一样。','Wánquán bù yīyàng.','Hoàn toàn không giống.'),
  _(440,'全部','quánbù','Toàn bộ',3,'adverb',12,'全部完成。','Quánbù wánchéng.','Toàn bộ hoàn thành.'),
  _(441,'所有','suǒyǒu','Tất cả',3,'adjective',12,'所有的人。','Suǒyǒu de rén.','Tất cả mọi người.'),
  _(442,'一样','yīyàng','Giống nhau',3,'adjective',10,'一样大。','Yīyàng dà.','Lớn bằng nhau.'),
  _(443,'不同','bùtóng','Khác nhau',3,'adjective',12,'不同颜色。','Bùtóng yánsè.','Màu sắc khác nhau.'),
  _(444,'一样','yīyàng','Cùng',3,'adjective',10,'一样好看。','Yīyàng hǎokàn.','Đẹp như nhau.'),
  _(445,'主要','zhǔyào','Chủ yếu',3,'adjective',10,'主要原因。','Zhǔyào yuányīn.','Nguyên nhân chính.'),
  _(446,'重要','zhòngyào','Quan trọng',3,'adjective',14,'最重要。','Zuì zhòngyào.','Quan trọng nhất.'),
  _(447,'必要','bìyào','Cần thiết',3,'adjective',12,'有必要。','Yǒu bìyào.','Có cần thiết.'),
  _(448,'行','xíng','Được',3,'adjective',6,'行不行？','Xíng bù xíng?','Được không?'),
  _(449,'一样','yīyàng','Giống',3,'adjective',10,'和以前一样。','Hé yǐqián yīyàng.','Giống như trước đây.'),
  _(450,'酸','suān','Chua',3,'adjective',14,'太酸了。','Tài suān le.','Chua quá.'),
  _(451,'甜','tián','Ngọt',3,'adjective',11,'太甜了。','Tài tián le.','Ngọt quá.'),
  _(452,'苦','kǔ','Đắng',3,'adjective',8,'太苦了。','Tài kǔ le.','Đắng quá.'),
  _(453,'辣','là','Cay',3,'adjective',14,'太辣了。','Tài là le.','Cay quá.'),
  _(454,'咸','xián','Mặn',3,'adjective',9,'太咸了。','Tài xián le.','Mặn quá.'),
  _(455,'新鲜','xīnxiān','Tươi',3,'adjective',19,'很新鲜。','Hěn xīnxiān.','Rất tươi.'),
  _(456,'好吃','hǎochī','Ngon',3,'adjective',13,'很好吃。','Hěn hǎochī.','Rất ngon.'),
  _(457,'渴','kě','Khát',3,'adjective',12,'我渴了。','Wǒ kě le.','Tôi khát rồi.'),
  _(458,'饿','è','Đói',3,'adjective',10,'我饿了。','Wǒ è le.','Tôi đói rồi.'),
  _(459,'饱','bǎo','No',3,'adjective',8,'吃饱了。','Chī bǎo le.','Ăn no rồi.'),
  _(460,'轻','qīng','Nhẹ',3,'adjective',9,'很轻。','Hěn qīng.','Rất nhẹ.'),
  _(461,'重','zhòng','Nặng',3,'adjective',9,'很重。','Hěn zhòng.','Rất nặng.'),
  _(462,'奇怪','qíguài','Kỳ lạ',3,'adjective',13,'很奇怪。','Hěn qíguài.','Rất kỳ lạ.'),
  _(463,'差','chà','Kém, Xấu',3,'adjective',9,'质量差。','Zhìliàng chà.','Chất lượng kém.'),
  _(464,'差不多','chàbuduō','Gần như',3,'adverb',15,'差不多好了。','Chàbuduō hǎo le.','Gần xong rồi.'),
  _(465,'地方','dìfang','Chỗ, Nơi',3,'noun',12,'这个地方。','Zhège dìfang.','Chỗ này.'),
  _(466,'风景','fēngjǐng','Phong cảnh',3,'noun',14,'风景很美。','Fēngjǐng hěn měi.','Phong cảnh rất đẹp.'),
  _(467,'季节','jìjié','Mùa',3,'noun',16,'四个季节。','Sì gè jìjié.','Bốn mùa.'),
  _(468,'春天','chūntiān','Mùa xuân',3,'noun',13,'春天来了。','Chūntiān lái le.','Mùa xuân đến rồi.'),
  _(469,'夏天','xiàtiān','Mùa hè',3,'noun',14,'夏天很热。','Xiàtiān hěn rè.','Mùa hè rất nóng.'),
  _(470,'秋天','qiūtiān','Mùa thu',3,'noun',13,'秋天凉快。','Qiūtiān liángkuai.','Mùa thu mát mẻ.'),
  _(471,'冬天','dōngtiān','Mùa đông',3,'noun',11,'冬天很冷。','Dōngtiān hěn lěng.','Mùa đông rất lạnh.'),
  _(472,'温度','wēndù','Nhiệt độ',3,'noun',16,'温度很高。','Wēndù hěn gāo.','Nhiệt độ rất cao.'),
  _(473,'颜色','yánsè','Màu sắc',3,'noun',15,'什么颜色？','Shénme yánsè?','Màu gì?'),
  _(474,'红色','hóngsè','Màu đỏ',3,'noun',12,'红色的花。','Hóngsè de huā.','Hoa màu đỏ.'),
  _(475,'蓝色','lánsè','Màu xanh',3,'noun',16,'蓝色的天空。','Lánsè de tiānkōng.','Bầu trời xanh.'),
  _(476,'绿色','lǜsè','Màu xanh lá',3,'noun',17,'绿色的草。','Lǜsè de cǎo.','Cỏ xanh.'),
  _(477,'白色','báisè','Màu trắng',3,'noun',12,'白色的雪。','Báisè de xuě.','Tuyết trắng.'),
  _(478,'黑色','hēisè','Màu đen',3,'noun',14,'黑色的头发。','Hēisè de tóufa.','Tóc đen.'),
  _(479,'黄色','huángsè','Màu vàng',3,'noun',16,'黄色的香蕉。','Huángsè de xiāngjiāo.','Chuối vàng.'),
  _(480,'样子','yàngzi','Dáng vẻ',3,'noun',14,'这个样子。','Zhège yàngzi.','Dáng vẻ này.'),
  _(481,'情况','qíngkuàng','Tình huống',3,'noun',15,'什么情况？','Shénme qíngkuàng?','Tình huống gì?'),
  _(482,'事情','shìqing','Sự việc',3,'noun',12,'有事吗？','Yǒu shì ma?','Có việc gì không?'),
  _(483,'问题','wèntí','Vấn đề',3,'noun',13,'没问题。','Méi wèntí.','Không vấn đề.'),
  _(484,'办法','bànfǎ','Biện pháp',3,'noun',12,'想办法。','Xiǎng bànfǎ.','Nghĩ cách.'),
  _(485,'原因','yuányīn','Nguyên nhân',3,'noun',14,'什么原因？','Shénme yuányīn?','Nguyên nhân gì?'),
  _(486,'结果','jiéguǒ','Kết quả',3,'noun',14,'结果是好的。','Jiéguǒ shì hǎo de.','Kết quả tốt.'),
  _(487,'目的','mùdì','Mục đích',3,'noun',9,'目的是学习。','Mùdì shì xuéxí.','Mục đích là học.'),
  _(488,'意见','yìjiàn','Ý kiến',3,'noun',11,'有什么意见？','Yǒu shénme yìjiàn?','Có ý kiến gì?'),
  _(489,'笑话','xiàohua','Chuyện cười',3,'noun',14,'讲笑话。','Jiǎng xiàohua.','Kể chuyện cười.'),
  _(490,'故事','gùshi','Câu chuyện',3,'noun',12,'讲故事。','Jiǎng gùshi.','Kể chuyện.'),
  _(491,'新闻','xīnwén','Tin tức',3,'noun',13,'看新闻。','Kàn xīnwén.','Xem tin tức.'),
  _(492,'广告','guǎnggào','Quảng cáo',3,'noun',11,'看广告。','Kàn guǎnggào.','Xem quảng cáo.'),
  _(493,'比赛','bǐsài','Thi đấu',3,'noun',11,'足球比赛。','Zúqiú bǐsài.','Trận bóng đá.'),
  _(494,'节目','jiémù','Chương trình',3,'noun',10,'什么节目？','Shénme jiémù?','Chương trình gì?'),
  _(495,'文化','wénhuà','Văn hóa',3,'noun',8,'中国文化。','Zhōngguó wénhuà.','Văn hóa Trung Quốc.'),
  _(496,'历史','lìshǐ','Lịch sử',3,'noun',8,'中国历史。','Zhōngguó lìshǐ.','Lịch sử Trung Quốc.'),
  _(497,'世界','shìjiè','Thế giới',3,'noun',10,'全世界。','Quán shìjiè.','Toàn thế giới.'),
  _(498,'国家','guójiā','Quốc gia',3,'noun',13,'很多国家。','Hěn duō guójiā.','Nhiều quốc gia.'),
  _(499,'城市','chéngshì','Thành phố',3,'noun',14,'大城市。','Dà chéngshì.','Thành phố lớn.'),
  _(500,'农村','nóngcūn','Nông thôn',3,'noun',12,'去农村。','Qù nóngcūn.','Về nông thôn.'),
  _(501,'公司','gōngsī','Công ty',3,'noun',8,'在公司工作。','Zài gōngsī gōngzuò.','Làm việc ở công ty.'),
  _(502,'办公室','bàngōngshì','Văn phòng',3,'noun',11,'在办公室。','Zài bàngōngshì.','Ở văn phòng.'),
  _(503,'楼','lóu','Tòa nhà, Tầng',3,'noun',13,'几楼？','Jǐ lóu?','Tầng mấy?'),
  _(504,'商店','shāngdiàn','Cửa hàng',3,'noun',16,'在商店。','Zài shāngdiàn.','Ở cửa hàng.'),
  _(505,'超市','chāoshì','Siêu thị',3,'noun',14,'去超市。','Qù chāoshì.','Đi siêu thị.'),
  _(506,'市场','shìchǎng','Chợ',3,'noun',11,'去市场。','Qù shìchǎng.','Đi chợ.'),
  _(507,'旅馆','lǚguǎn','Khách sạn',3,'noun',15,'住旅馆。','Zhù lǚguǎn.','Ở khách sạn.'),
  _(508,'饭馆','fànguǎn','Nhà hàng',3,'noun',14,'去饭馆。','Qù fànguǎn.','Đi nhà hàng.'),
  _(509,'食堂','shítáng','Căn tin',3,'noun',14,'在食堂吃饭。','Zài shítáng chīfàn.','Ăn ở căn tin.'),
  _(510,'厨房','chúfáng','Phòng bếp',3,'noun',12,'在厨房做饭。','Zài chúfáng zuòfàn.','Nấu ăn trong bếp.'),
  _(511,'卧室','wòshì','Phòng ngủ',3,'noun',13,'在卧室睡觉。','Zài wòshì shuìjiào.','Ngủ trong phòng ngủ.'),
  _(512,'客厅','kètīng','Phòng khách',3,'noun',12,'在客厅看电视。','Zài kètīng kàn diànshì.','Xem tivi ở phòng khách.'),
  _(513,'卫生间','wèishēngjiān','Nhà vệ sinh',3,'noun',14,'在卫生间。','Zài wèishēngjiān.','Ở nhà vệ sinh.'),
  _(514,'阳台','yángtái','Ban công',3,'noun',12,'在阳台。','Zài yángtái.','Ở ban công.'),
  _(515,'花园','huāyuán','Vườn hoa',3,'noun',12,'在花园散步。','Zài huāyuán sànbù.','Đi dạo trong vườn.'),
  _(516,'门口','ménkǒu','Cửa ra vào',3,'noun',11,'在门口见。','Zài ménkǒu jiàn.','Gặp ở cửa.'),
  _(517,'窗户外','chuānghu wài','Ngoài cửa sổ',3,'noun',17,'窗户外面。','Chuānghu wàimiàn.','Bên ngoài cửa sổ.'),
  _(518,'上面','shàngmiàn','Phía trên',3,'noun',9,'桌子上面。','Zhuōzi shàngmiàn.','Trên bàn.'),
  _(519,'下面','xiàmiàn','Phía dưới',3,'noun',8,'椅子下面。','Yǐzi xiàmiàn.','Dưới ghế.'),
  _(520,'前面','qiánmiàn','Phía trước',3,'noun',12,'前面有人。','Qiánmiàn yǒu rén.','Phía trước có người.'),
  _(521,'后面','hòumiàn','Phía sau',3,'noun',11,'后面有车。','Hòumiàn yǒu chē.','Phía sau có xe.'),
  _(522,'左边','zuǒbiān','Bên trái',3,'noun',9,'左边是银行。','Zuǒbiān shì yínháng.','Bên trái là ngân hàng.'),
  _(523,'右边','yòubiān','Bên phải',3,'noun',9,'右边是商店。','Yòubiān shì shāngdiàn.','Bên phải là cửa hàng.'),
  _(524,'旁边','pángbiān','Bên cạnh',3,'noun',16,'旁边有人。','Pángbiān yǒu rén.','Bên cạnh có người.'),
  _(525,'中间','zhōngjiān','Ở giữa',3,'noun',10,'中间有桌子。','Zhōngjiān yǒu zhuōzi.','Ở giữa có bàn.'),
  _(526,'对面','duìmiàn','Đối diện',3,'noun',13,'对面是超市。','Duìmiàn shì chāoshì.','Đối diện là siêu thị.'),
  _(527,'附近','fùjìn','Gần',3,'noun',12,'附近有地铁。','Fùjìn yǒu dìtiě.','Gần có tàu điện ngầm.'),
  _(528,'过去','guòqù','Quá khứ',3,'noun',14,'过去的事。','Guòqù de shì.','Chuyện quá khứ.'),
  _(529,'未来','wèilái','Tương lai',3,'noun',11,'美好的未来。','Měihǎo de wèilái.','Tương lai tươi đẹp.'),
  _(530,'开始','kāishǐ','Bắt đầu',3,'verb',12,'开始上课。','Kāishǐ shàngkè.','Bắt đầu lên lớp.'),
  _(531,'结束','jiéshù','Kết thúc',3,'verb',17,'下课了。','Xiàkè le.','Tan học rồi.'),
  _(532,'毕业','bìyè','Tốt nghiệp',3,'verb',11,'大学毕业。','Dàxué bìyè.','Tốt nghiệp đại học.'),
  _(533,'留学','liúxué','Du học',3,'verb',16,'去留学。','Qù liúxué.','Đi du học.'),
  _(534,'奖学金','jiǎngxuéjīn','Học bổng',3,'noun',14,'拿奖学金。','Ná jiǎngxuéjīn.','Nhận học bổng.'),
  _(535,'成绩','chéngjì','Thành tích',3,'noun',11,'成绩很好。','Chéngjì hěn hǎo.','Thành tích rất tốt.'),
  _(536,'水平','shuǐpíng','Trình độ',3,'noun',12,'水平很高。','Shuǐpíng hěn gāo.','Trình độ rất cao.'),
  _(537,'语法','yǔfǎ','Ngữ pháp',3,'noun',13,'学语法。','Xué yǔfǎ.','Học ngữ pháp.'),
  _(538,'发音','fāyīn','Phát âm',3,'noun',10,'发音标准。','Fāyīn biāozhǔn.','Phát âm chuẩn.'),
  _(539,'声调','shēngdiào','Thanh điệu',3,'noun',12,'四个声调。','Sì gè shēngdiào.','Bốn thanh điệu.'),
  _(540,'意思','yìsi','Ý nghĩa',3,'noun',13,'什么意思？','Shénme yìsi?','Ý nghĩa gì?'),
  _(541,'翻译','fānyì','Dịch',3,'verb',17,'翻译成中文。','Fānyì chéng Zhōngwén.','Dịch sang tiếng Trung.'),
  _(542,'练习','liànxí','Luyện tập',3,'verb',15,'练习发音。','Liànxí fāyīn.','Luyện phát âm.'),
  _(543,'复习','fùxí','Ôn tập',3,'verb',14,'复习生词。','Fùxí shēngcí.','Ôn từ mới.'),
  _(544,'预习','yùxí','Xem bài trước',3,'verb',13,'预习课文。','Yùxí kèwén.','Xem trước bài học.'),
  _(545,'要求','yāoqiú','Yêu cầu',3,'verb',15,'要求很高。','Yāoqiú hěn gāo.','Yêu cầu rất cao.'),
  _(546,'保证','bǎozhèng','Bảo đảm',3,'verb',14,'保证完成。','Bǎozhèng wánchéng.','Bảo đảm hoàn thành.'),
  _(547,'愿意','yuànyì','Bằng lòng',3,'verb',18,'我愿意学习。','Wǒ yuànyì xuéxí.','Tôi bằng lòng học.'),
  _(548,'敢','gǎn','Dám',3,'verb',11,'不敢去。','Bù gǎn qù.','Không dám đi.'),
  _(549,'应该','yīnggāi','Nên',3,'verb',15,'应该努力。','Yīnggāi nǔlì.','Nên cố gắng.'),
  _(550,'需要','xūyào','Cần',3,'verb',14,'需要帮助。','Xūyào bāngzhù.','Cần giúp đỡ.'),
  _(551,'麻烦','máfan','Phiền phức',3,'adjective',17,'很麻烦。','Hěn máfan.','Rất phiền phức.'),
  _(552,'小心','xiǎoxīn','Cẩn thận',3,'adjective',9,'小心点。','Xiǎoxīn diǎn.','Cẩn thận.'),
  _(553,'安全','ānquán','An toàn',3,'adjective',12,'注意安全。','Zhùyì ānquán.','Chú ý an toàn.'),
  _(554,'危险','wēixiǎn','Nguy hiểm',3,'adjective',12,'很危险。','Hěn wēixiǎn.','Nguy hiểm.'),
  _(555,'着急','zháojí','Sốt ruột',3,'adjective',16,'别着急。','Bié zháojí.','Đừng sốt ruột.'),
  _(556,'紧张','jǐnzhāng','Căng thẳng',3,'adjective',16,'别紧张。','Bié jǐnzhāng.','Đừng căng thẳng.'),
  _(557,'放松','fàngsōng','Thư giãn',3,'verb',14,'放松一下。','Fàngsōng yīxià.','Thư giãn một chút.'),
  _(558,'幸福','xìngfú','Hạnh phúc',3,'adjective',15,'真幸福。','Zhēn xìngfú.','Thật hạnh phúc.'),
  _(559,'生气','shēngqì','Tức giận',3,'verb',12,'别生气。','Bié shēngqì.','Đừng giận.'),
  _(560,'难过','nánguò','Buồn',3,'adjective',16,'别难过。','Bié nánguò.','Đừng buồn.'),
  _(561,'感动','gǎndòng','Cảm động',3,'verb',15,'很感动。','Hěn gǎndòng.','Rất cảm động.'),
  _(562,'满意','mǎnyì','Hài lòng',3,'adjective',17,'很满意。','Hěn mǎnyì.','Rất hài lòng.'),
  _(563,'惊讶','jīngyà','Ngạc nhiên',3,'adjective',15,'很惊讶。','Hěn jīngyà.','Rất ngạc nhiên.'),
  _(564,'害怕','hàipà','Sợ',3,'verb',13,'别害怕。','Bié hàipà.','Đừng sợ.'),
  _(565,'骄傲','jiāo ào','Tự hào',3,'adjective',16,'很骄傲。','Hěn jiāo ào.','Rất tự hào.'),
  _(566,'谦虚','qiānxū','Khiêm tốn',3,'adjective',18,'很谦虚。','Hěn qiānxū.','Rất khiêm tốn.'),
  _(567,'聪明','cōngming','Thông minh',3,'adjective',17,'很聪明。','Hěn cōngming.','Rất thông minh.'),
  _(568,'可爱','kě ài','Đáng yêu',3,'adjective',12,'真可爱。','Zhēn kě ài.','Thật đáng yêu.'),
  _(569,'勇敢','yǒnggǎn','Dũng cảm',3,'adjective',16,'很勇敢。','Hěn yǒnggǎn.','Rất dũng cảm.'),
  _(570,'善良','shànliáng','Lương thiện',3,'adjective',16,'很善良。','Hěn shànliáng.','Rất lương thiện.'),
  _(571,'诚实','chéngshí','Thành thật',3,'adjective',14,'很诚实。','Hěn chéngshí.','Rất thành thật.'),
  _(572,'努力','nǔlì','Cố gắng',3,'adjective',13,'很努力。','Hěn nǔlì.','Rất cố gắng.'),
  _(573,'感动','gǎndòng','Cảm động',3,'adjective',15,'很感动。','Hěn gǎndòng.','Rất cảm động.'),
  _(574,'热情','rèqíng','Nhiệt tình',3,'adjective',15,'很热情。','Hěn rèqíng.','Rất nhiệt tình.'),
  _(575,'友好','yǒuhǎo','Thân thiện',3,'adjective',11,'很友好。','Hěn yǒuhǎo.','Rất thân thiện.'),
  _(576,'方便','fāngbiàn','Tiện lợi',3,'adjective',13,'很方便。','Hěn fāngbiàn.','Rất tiện.'),
  _(577,'正好','zhènghǎo','Vừa đúng',3,'adverb',12,'正好十点。','Zhènghǎo shí diǎn.','Đúng 10 giờ.'),
  _(578,'其实','qíshí','Thực ra',3,'adverb',12,'其实不想去。','Qíshí bù xiǎng qù.','Thực ra không muốn đi.'),
  _(579,'尤其','yóuqí','Đặc biệt là',3,'adverb',12,'尤其是我。','Yóuqí shì wǒ.','Đặc biệt là tôi.'),
  _(580,'非常','fēicháng','Vô cùng',3,'adverb',16,'非常重要。','Fēicháng zhòngyào.','Vô cùng quan trọng.'),
  _(581,'特别','tèbié','Đặc biệt',3,'adverb',14,'特别喜欢。','Tèbié xǐhuān.','Đặc biệt thích.'),
  _(582,'比较','bǐjiào','Khá',3,'adverb',8,'比较好。','Bǐjiào hǎo.','Khá tốt.'),
  _(583,'更加','gèngjiā','Càng thêm',3,'adverb',12,'更加努力。','Gèngjiā nǔlì.','Càng cố gắng hơn.'),
  _(584,'多么','duōme','Biết bao',3,'adverb',11,'多么漂亮！','Duōme piàoliang!','Đẹp biết bao!'),
  _(585,'快','kuài','Nhanh',3,'adverb',7,'快来。','Kuài lái.','Nhanh đến.'),
  _(586,'慢慢','mànmàn','Từ từ',3,'adverb',18,'慢慢走。','Mànmàn zǒu.','Từ từ đi.'),
  _(587,'常常','chángcháng','Thường xuyên',3,'adverb',15,'常常去。','Chángcháng qù.','Thường xuyên đi.'),
  _(588,'有时','yǒushí','Có lúc',3,'adverb',12,'有时来。','Yǒushí lái.','Có lúc đến.'),
  _(589,'总是','zǒngshì','Luôn',3,'adverb',14,'总是迟到。','Zǒngshì chídào.','Luôn đến muộn.'),
  _(590,'每天','měitiān','Mỗi ngày',3,'adverb',12,'每天学习。','Měitiān xuéxí.','Mỗi ngày học.'),
  _(591,'每年','měinián','Mỗi năm',3,'adverb',11,'每年旅游。','Měinián lǚyóu.','Mỗi năm đi du lịch.'),
  _(592,'每人','měirén','Mỗi người',3,'adverb',11,'每人一本。','Měirén yī běn.','Mỗi người một quyển.'),
  _(593,'到处','dàochù','Khắp nơi',3,'adverb',13,'到处是人。','Dàochù shì rén.','Khắp nơi là người.'),
  _(594,'互相','hùxiāng','Lẫn nhau',3,'adverb',8,'互相帮助。','Hùxiāng bāngzhù.','Giúp đỡ lẫn nhau.'),
  _(595,'一起','yīqǐ','Cùng',3,'adverb',10,'一起学习。','Yīqǐ xuéxí.','Cùng học.'),
  _(596,'从来','cónglái','Từ trước',3,'adverb',14,'从来不抽烟。','Cónglái bù chōuyān.','Chưa hút thuốc.'),
  _(597,'刚','gāng','Vừa mới',3,'adverb',6,'刚来。','Gāng lái.','Vừa mới đến.'),
  _(598,'刚刚','gānggāng','Vừa mới',3,'adverb',12,'刚刚开始。','Gānggāng kāishǐ.','Vừa mới bắt đầu.'),
  _(599,'才','cái','Mới',3,'adverb',3,'才八点。','Cái bā diǎn.','Mới 8 giờ.'),
  _(600,'就','jiù','Liền',3,'adverb',12,'就来。','Jiù lái.','Liền đến.'),
  _(601,'还','hái','Còn',3,'adverb',7,'还在。','Hái zài.','Còn ở đây.'),
  _(602,'再','zài','Lại',3,'adverb',6,'再来一次。','Zài lái yī cì.','Lại một lần nữa.'),
  _(603,'又','yòu','Lại',3,'adverb',2,'又下雨了。','Yòu xià yǔ le.','Lại mưa rồi.'),
  _(604,'也','yě','Cũng',3,'adverb',3,'我也去。','Wǒ yě qù.','Tôi cũng đi.'),
  _(605,'一定','yīdìng','Nhất định',3,'adverb',10,'一定来。','Yīdìng lái.','Nhất định đến.'),
  _(606,'真的','zhēnde','Thật sự',3,'adverb',16,'真的吗？','Zhēn de ma?','Thật không?'),
  _(607,'当然','dāngrán','Dĩ nhiên',3,'adverb',12,'当然可以。','Dāngrán kěyǐ.','Dĩ nhiên là được.'),
  _(608,'可能','kěnéng','Có lẽ',3,'adverb',13,'可能下雨。','Kěnéng xià yǔ.','Có lẽ mưa.'),
  _(609,'大概','dàgài','Khoảng',3,'adverb',11,'大概十点。','Dàgài shí diǎn.','Khoảng 10 giờ.'),
  _(610,'也许','yěxǔ','Có lẽ',3,'adverb',11,'也许可以。','Yěxǔ kěyǐ.','Có lẽ được.'),
  _(611,'差不多','chàbuduō','Gần như',3,'adverb',15,'差不多好了。','Chàbuduō hǎo le.','Gần xong.'),
  _(612,'所有','suǒyǒu','Tất cả',3,'adjective',12,'所有人。','Suǒyǒu rén.','Tất cả mọi người.'),
  _(613,'全部','quánbù','Toàn bộ',3,'adjective',12,'全部吃完。','Quánbù chī wán.','Ăn hết toàn bộ.'),
  _(614,'许多','xǔduō','Nhiều',3,'adjective',12,'许多人。','Xǔduō rén.','Nhiều người.'),
  _(615,'各种','gèzhǒng','Các loại',3,'adjective',12,'各种颜色。','Gèzhǒng yánsè.','Các loại màu.'),
  _(616,'主要','zhǔyào','Chủ yếu',3,'adjective',10,'主要目的。','Zhǔyào mùdì.','Mục đích chính.'),
  _(617,'重要','zhòngyào','Quan trọng',3,'adjective',14,'最重要。','Zuì zhòngyào.','Quan trọng nhất.'),
  _(618,'一样','yīyàng','Giống nhau',3,'adjective',10,'一样大。','Yīyàng dà.','Lớn bằng nhau.'),
  _(619,'不同','bùtóng','Khác',3,'adjective',12,'不同颜色。','Bùtóng yánsè.','Màu khác.'),
  _(620,'一样','yīyàng','Cùng',3,'adjective',10,'一样好。','Yīyàng hǎo.','Tốt như nhau.'),
  _(621,'对','duì','Đúng',3,'adjective',5,'你说得对。','Nǐ shuō de duì.','Bạn nói đúng.'),
  _(622,'错','cuò','Sai',3,'adjective',13,'你错了。','Nǐ cuò le.','Bạn sai rồi.'),
  _(623,'清楚','qīngchu','Rõ ràng',3,'adjective',17,'说清楚。','Shuō qīngchu.','Nói rõ ràng.'),
  _(624,'明白','míngbai','Hiểu rõ',3,'adjective',12,'说明白。','Shuō míngbai.','Nói rõ.'),
  _(625,'复杂','fùzá','Phức tạp',3,'adjective',14,'很复杂。','Hěn fùzá.','Rất phức tạp.'),
  _(626,'简单','jiǎndān','Đơn giản',3,'adjective',18,'很简单。','Hěn jiǎndān.','Rất đơn giản.'),
  _(627,'容易','róngyì','Dễ',3,'adjective',14,'很容易。','Hěn róngyì.','Rất dễ.'),
  _(628,'难','nán','Khó',3,'adjective',10,'很难。','Hěn nán.','Rất khó.'),
  _(629,'快','kuài','Nhanh',3,'adjective',7,'很快。','Hěn kuài.','Rất nhanh.'),
  _(630,'慢','màn','Chậm',3,'adjective',14,'很慢。','Hěn màn.','Rất chậm.'),
  _(631,'急','jí','Gấp',3,'adjective',9,'不用急。','Bùyòng jí.','Không cần gấp.'),
  _(632,'顺利','shùnlì','Suôn sẻ',3,'adjective',15,'一切顺利。','Yīqiè shùnlì.','Mọi việc suôn sẻ.'),
  _(633,'合适','héshì','Phù hợp',3,'adjective',14,'大小合适。','Dàxiǎo héshì.','Kích cỡ phù hợp.'),
  _(634,'舒服','shūfu','Thoải mái',3,'adjective',22,'很舒服。','Hěn shūfu.','Rất thoải mái.'),
  _(635,'好看','hǎokàn','Đẹp',3,'adjective',13,'真好看。','Zhēn hǎokàn.','Đẹp thật.'),
  _(636,'好听','hǎotīng','Hay (nghe)',3,'adjective',14,'这首歌好听。','Zhè shǒu gē hǎotīng.','Bài hát này hay.'),
  _(637,'好玩','hǎowán','Vui',3,'adjective',13,'很好玩。','Hěn hǎowán.','Rất vui.'),
  _(638,'有用','yǒuyòng','Có ích',3,'adjective',11,'很有用。','Hěn yǒuyòng.','Rất có ích.'),
  _(639,'有名','yǒumíng','Nổi tiếng',3,'adjective',13,'很有名。','Hěn yǒumíng.','Rất nổi tiếng.'),
  _(640,'无聊','wúliáo','Chán',3,'adjective',16,'很无聊。','Hěn wúliáo.','Rất chán.'),
  _(641,'难过','nánguò','Buồn',3,'adjective',16,'很难过。','Hěn nánguò.','Rất buồn.'),
  _(642,'开心','kāixīn','Vui vẻ',3,'adjective',12,'很开心。','Hěn kāixīn.','Rất vui.'),
  _(643,'难过','nánguò','Đau lòng',3,'adjective',16,'别难过。','Bié nánguò.','Đừng buồn.'),
  _(644,'感冒','gǎnmào','Cảm',3,'noun',19,'感冒了。','Gǎnmào le.','Cảm rồi.'),
  _(645,'发烧','fāshāo','Sốt',3,'verb',15,'发烧了。','Fāshāo le.','Sốt rồi.'),
  _(646,'咳嗽','késou','Ho',3,'verb',17,'咳嗽了。','Késou le.','Ho rồi.'),
  _(647,'头疼','tóuténg','Đau đầu',3,'noun',13,'我头疼。','Wǒ tóuténg.','Tôi đau đầu.'),
  _(648,'牙疼','yáténg','Đau răng',3,'noun',14,'牙疼了。','Yáténg le.','Đau răng rồi.'),
  _(649,'肚子疼','dùziténg','Đau bụng',3,'noun',17,'肚子疼。','Dùziténg.','Đau bụng.'),
  _(650,'生病','shēngbìng','Ốm',3,'verb',12,'生病了。','Shēngbìng le.','Ốm rồi.'),
  _(651,'看病','kànbìng','Khám bệnh',3,'verb',15,'去医院看病。','Qù yīyuàn kànbìng.','Đi bệnh viện khám.'),
  _(652,'住院','zhùyuàn','Nhập viện',3,'verb',15,'住院了。','Zhùyuàn le.','Nhập viện rồi.'),
  _(653,'出院','chūyuàn','Xuất viện',3,'verb',13,'出院了。','Chūyuàn le.','Xuất viện rồi.'),
  _(654,'手术','shǒushù','Phẫu thuật',3,'noun',11,'做手术。','Zuò shǒushù.','Làm phẫu thuật.'),
  _(655,'体检','tǐjiǎn','Kiểm tra sức khỏe',3,'noun',15,'做体检。','Zuò tǐjiǎn.','Kiểm tra sức khỏe.'),
  _(656,'锻炼','duànliàn','Rèn luyện',3,'verb',17,'锻炼身体。','Duànliàn shēntǐ.','Rèn luyện sức khỏe.'),
  _(657,'减肥','jiǎnféi','Giảm cân',3,'verb',14,'减肥。','Jiǎnféi.','Giảm cân.'),
  _(658,'胖','pàng','Mập',3,'adjective',9,'太胖了。','Tài pàng le.','Mập quá.'),
  _(659,'瘦','shòu','Ốm',3,'adjective',14,'太瘦了。','Tài shòu le.','Ốm quá.'),
  _(660,'身高','shēngāo','Chiều cao',3,'noun',15,'身高多少？','Shēngāo duōshao?','Cao bao nhiêu?'),
  _(661,'体重','tǐzhòng','Cân nặng',3,'noun',15,'体重多少？','Tǐzhòng duōshao?','Nặng bao nhiêu?'),
  _(662,'结婚','jiéhūn','Kết hôn',3,'verb',15,'结婚了。','Jiéhūn le.','Kết hôn rồi.'),
  _(663,'离婚','líhūn','Ly hôn',3,'verb',14,'离婚了。','Líhūn le.','Ly hôn rồi.'),
  _(664,'出生','chūshēng','Sinh ra',3,'verb',11,'出生在越南。','Chūshēng zài Yuènán.','Sinh ra ở Việt Nam.'),
  _(665,'长大','zhǎngdà','Lớn lên',3,'verb',11,'在越南长大。','Zài Yuènán zhǎngdà.','Lớn lên ở Việt Nam.'),
  _(666,'生活','shēnghuó','Cuộc sống',3,'noun',12,'生活很幸福。','Shēnghuó hěn xìngfú.','Cuộc sống hạnh phúc.'),
  _(667,'习惯','xíguàn','Thói quen',3,'noun',12,'好习惯。','Hǎo xíguàn.','Thói quen tốt.'),
  _(668,'爱好','àihào','Sở thích',3,'noun',14,'你的爱好是什么？','Nǐ de àihào shì shénme?','Sở thích của bạn là gì?'),
  _(669,'兴趣','xìngqù','Hứng thú',3,'noun',14,'有兴趣。','Yǒu xìngqù.','Có hứng thú.'),
  _(670,'梦想','mèngxiǎng','Ước mơ',3,'noun',17,'我的梦想。','Wǒ de mèngxiǎng.','Ước mơ của tôi.'),
  // giao tiếp đời sống bổ sung
  _(1401,'沟通','gōutōng','Giao tiếp',3,'verb',12,'沟通很重要。','Gōutōng hěn zhòngyào.','Giao tiếp rất quan trọng.'),
  _(1402,'协商','xiéshāng','Thương lượng',3,'verb',14,'我们可以协商价格。','Wǒmen kěyǐ xiéshāng jiàgé.','Chúng ta có thể thương lượng giá.'),
  _(1403,'误会','wùhuì','Hiểu lầm',3,'noun',10,'这是一场误会。','Zhè shì yì chǎng wùhuì.','Đây là một hiểu lầm.'),
  _(1404,'道歉','dàoqiàn','Xin lỗi (trang trọng)',3,'verb',16,'我为迟到道歉。','Wǒ wèi chídào dàoqiàn.','Tôi xin lỗi vì đến muộn.'),
  _(1405,'原谅','yuánliàng','Tha thứ',3,'verb',15,'请原谅我的错误。','Qǐng yuánliàng wǒ de cuòwù.','Xin hãy tha thứ lỗi của tôi.'),
  _(1406,'反馈','fǎnkuì','Phản hồi',3,'noun',16,'谢谢你的反馈。','Xièxie nǐ de fǎnkuì.','Cảm ơn phản hồi của bạn.'),
  _(1407,'确认','quèrèn','Xác nhận',3,'verb',15,'请确认一下地址。','Qǐng quèrèn yíxià dìzhǐ.','Xin xác nhận lại địa chỉ.'),
  _(1408,'取消','qǔxiāo','Hủy',3,'verb',13,'我想取消预约。','Wǒ xiǎng qǔxiāo yùyuē.','Tôi muốn hủy lịch hẹn.'),
  _(1409,'改期','gǎiqī','Đổi lịch',3,'verb',14,'会议需要改期。','Huìyì xūyào gǎiqī.','Cuộc họp cần đổi lịch.'),
  _(1410,'准时','zhǔnshí','Đúng giờ',3,'adjective',15,'请你准时到。','Qǐng nǐ zhǔnshí dào.','Bạn hãy đến đúng giờ.'),
  _(1411,'迟到','chídào','Đến muộn',3,'verb',5,'今天我迟到了。','Jīntiān wǒ chídào le.','Hôm nay tôi đến muộn.'),
  _(1412,'合作','hézuò','Hợp tác',3,'verb',10,'希望我们合作愉快。','Xīwàng wǒmen hézuò yúkuài.','Hy vọng chúng ta hợp tác vui vẻ.'),
];

// ─── HSK 4: id 671–970 (300 từ mới) ─────────────────────────
export const hsk4 = [
  _(671,'数字','shùzì','Số',4,'noun',17,'学数字。','Xué shùzì.','Học số.'),
  _(672,'号码','hàomǎ','Số hiệu',4,'noun',11,'手机号码。','Shǒujī hàomǎ.','Số điện thoại.'),
  _(673,'价钱','jiàqián','Giá cả',4,'noun',13,'价钱很贵。','Jiàqián hěn guì.','Giá rất đắt.'),
  _(674,'价格','jiàgé','Giá',4,'noun',12,'价格合理。','Jiàgé hélǐ.','Giá hợp lý.'),
  _(675,'免费','miǎnfèi','Miễn phí',4,'adjective',12,'免费入场。','Miǎnfèi rùchǎng.','Vào cửa miễn phí.'),
  _(676,'优惠','yōuhuì','Ưu đãi',4,'noun',12,'有优惠吗？','Yǒu yōuhuì ma?','Có ưu đãi không?'),
  _(677,'打折','dǎzhé','Giảm giá',4,'verb',12,'打折了。','Dǎzhé le.','Giảm giá rồi.'),
  _(678,'发票','fāpiào','Hóa đơn',4,'noun',11,'开发票。','Kāi fāpiào.','Xuất hóa đơn.'),
  _(679,'收据','shōujù','Biên lai',4,'noun',16,'拿收据。','Ná shōujù.','Lấy biên lai.'),
  _(680,'信用卡','xìnyòngkǎ','Thẻ tín dụng',4,'noun',17,'用信用卡。','Yòng xìnyòngkǎ.','Dùng thẻ tín dụng.'),
  _(681,'现金','xiànjīn','Tiền mặt',4,'noun',14,'付现金。','Fù xiànjīn.','Trả tiền mặt.'),
  _(682,'零钱','língqián','Tiền lẻ',4,'noun',16,'换零钱。','Huàn língqián.','Đổi tiền lẻ.'),
  _(683,'钱包','qiánbāo','Ví',4,'noun',15,'我的钱包。','Wǒ de qiánbāo.','Ví của tôi.'),
  _(684,'工资','gōngzī','Lương',4,'noun',13,'发工资。','Fā gōngzī.','Phát lương.'),
  _(685,'收入','shōurù','Thu nhập',4,'noun',10,'收入很高。','Shōurù hěn gāo.','Thu nhập cao.'),
  _(686,'消费','xiāofèi','Tiêu dùng',4,'verb',16,'消费水平。','Xiāofèi shuǐpíng.','Mức tiêu dùng.'),
  _(687,'节约','jiéyuē','Tiết kiệm',4,'verb',11,'节约用水。','Jiéyuē yòng shuǐ.','Tiết kiệm nước.'),
  _(688,'浪费','làngfèi','Lãng phí',4,'verb',16,'别浪费。','Bié làngfèi.','Đừng lãng phí.'),
  _(689,'经济','jīngjì','Kinh tế',4,'noun',13,'经济发展。','Jīngjì fāzhǎn.','Phát triển kinh tế.'),
  _(690,'发展','fāzhǎn','Phát triển',4,'verb',13,'发展经济。','Fāzhǎn jīngjì.','Phát triển kinh tế.'),
  _(691,'进步','jìnbù','Tiến bộ',4,'verb',12,'进步很快。','Jìnbù hěn kuài.','Tiến bộ nhanh.'),
  _(692,'提高','tígāo','Nâng cao',4,'verb',17,'提高水平。','Tígāo shuǐpíng.','Nâng cao trình độ.'),
  _(693,'降低','jiàngdī','Giảm xuống',4,'verb',13,'降低价格。','Jiàngdī jiàgé.','Giảm giá.'),
  _(694,'增加','zēngjiā','Tăng thêm',4,'verb',14,'增加数量。','Zēngjiā shùliàng.','Tăng số lượng.'),
  _(695,'减少','jiǎnshǎo','Giảm bớt',4,'verb',12,'减少开支。','Jiǎnshǎo kāizhī.','Giảm chi tiêu.'),
  _(696,'变化','biànhuà','Thay đổi',4,'verb',14,'变化很大。','Biànhuà hěn dà.','Thay đổi lớn.'),
  _(697,'调查','diàochá','Điều tra',4,'verb',15,'做调查。','Zuò diàochá.','Làm điều tra.'),
  _(698,'研究','yánjiū','Nghiên cứu',4,'verb',14,'研究问题。','Yánjiū wèntí.','Nghiên cứu vấn đề.'),
  _(699,'科学','kēxué','Khoa học',4,'noun',13,'科学技术。','Kēxué jìshù.','Khoa học kỹ thuật.'),
  _(700,'技术','jìshù','Kỹ thuật',4,'noun',10,'技术发达。','Jìshù fādá.','Kỹ thuật phát triển.'),
  _(701,'电脑','diànnǎo','Máy tính',4,'noun',10,'用电脑。','Yòng diànnǎo.','Dùng máy tính.'),
  _(702,'网络','wǎngluò','Mạng',4,'noun',13,'网络很快。','Wǎngluò hěn kuài.','Mạng nhanh.'),
  _(703,'网址','wǎngzhǐ','Địa chỉ web',4,'noun',13,'发网址。','Fā wǎngzhǐ.','Gửi địa chỉ web.'),
  _(704,'网站','wǎngzhàn','Website',4,'noun',14,'上网站。','Shàng wǎngzhàn.','Lên website.'),
  _(705,'邮箱','yóuxiāng','Hộp thư',4,'noun',13,'发邮箱。','Fā yóuxiāng.','Gửi email.'),
  _(706,'邮件','yóujiàn','Thư điện tử',4,'noun',13,'发邮件。','Fā yóujiàn.','Gửi email.'),
  _(707,'短信','duǎnxìn','Tin nhắn',4,'noun',18,'发短信。','Fā duǎnxìn.','Gửi tin nhắn.'),
  _(708,'微信','Wēixìn','WeChat',4,'noun',18,'用微信。','Yòng Wēixìn.','Dùng WeChat.'),
  _(709,'支付','zhīfù','Thanh toán',4,'verb',10,'用微信支付。','Yòng Wēixìn zhīfù.','Thanh toán bằng WeChat.'),
  _(710,'密码','mìmǎ','Mật khẩu',4,'noun',14,'输入密码。','Shūrù mìmǎ.','Nhập mật khẩu.'),
  _(711,'账号','zhànghào','Tài khoản',4,'noun',12,'银行账号。','Yínháng zhànghào.','Số tài khoản ngân hàng.'),
  _(712,'软件','ruǎnjiàn','Phần mềm',4,'noun',11,'安装软件。','Ānzhuāng ruǎnjiàn.','Cài phần mềm.'),
  _(713,'硬件','yìngjiàn','Phần cứng',4,'noun',14,'电脑硬件。','Diànnǎo yìngjiàn.','Phần cứng máy tính.'),
  _(714,'信息','xìnxī','Thông tin',4,'noun',14,'发信息。','Fā xìnxī.','Gửi thông tin.'),
  _(715,'知识','zhīshi','Kiến thức',4,'noun',11,'学知识。','Xué zhīshi.','Học kiến thức.'),
  _(716,'经验','jīngyàn','Kinh nghiệm',4,'noun',13,'有经验。','Yǒu jīngyàn.','Có kinh nghiệm.'),
  _(717,'能力','nénglì','Năng lực',4,'noun',12,'有能力。','Yǒu nénglì.','Có năng lực.'),
  _(718,'本领','běnlǐng','Bản lĩnh',4,'noun',11,'有本领。','Yǒu běnlǐng.','Có bản lĩnh.'),
  _(719,'成功','chénggōng','Thành công',4,'adjective',12,'很成功。','Hěn chénggōng.','Rất thành công.'),
  _(720,'失败','shībài','Thất bại',4,'verb',11,'不失败。','Bù shībài.','Không thất bại.'),
  _(721,'实现','shíxiàn','Thực hiện',4,'verb',13,'实现梦想。','Shíxiàn mèngxiǎng.','Thực hiện ước mơ.'),
  _(722,'达到','dádào','Đạt được',4,'verb',12,'达到目标。','Dádào mùbiāo.','Đạt mục tiêu.'),
  _(723,'超过','chāoguò','Vượt qua',4,'verb',14,'超过别人。','Chāoguò biérén.','Vượt qua người khác.'),
  _(724,'继续','jìxù','Tiếp tục',4,'verb',16,'继续努力。','Jìxù nǔlì.','Tiếp tục cố gắng.'),
  _(725,'保持','bǎochí','Giữ',4,'verb',14,'保持安静。','Bǎochí ānjìng.','Giữ yên lặng.'),
  _(726,'坚持','jiānchí','Kiên trì',4,'verb',15,'坚持到底。','Jiānchí dàodǐ.','Kiên trì đến cùng.'),
  _(727,'重视','zhòngshì','Chú trọng',4,'verb',12,'重视学习。','Zhòngshì xuéxí.','Chú trọng học tập.'),
  _(728,'注意','zhùyì','Chú ý',4,'verb',13,'注意听。','Zhùyì tīng.','Chú ý nghe.'),
  _(729,'关心','guānxīn','Quan tâm',4,'verb',12,'关心别人。','Guānxīn biérén.','Quan tâm người khác.'),
  _(730,'负责','fùzé','Phụ trách',4,'verb',12,'负责工作。','Fùzé gōngzuò.','Phụ trách công việc.'),
  _(731,'管理','guǎnlǐ','Quản lý',4,'verb',18,'管理公司。','Guǎnlǐ gōngsī.','Quản lý công ty.'),
  _(732,'安排','ānpái','Sắp xếp',4,'verb',12,'安排时间。','Ānpái shíjiān.','Sắp xếp thời gian.'),
  _(733,'处理','chǔlǐ','Xử lý',4,'verb',9,'处理问题。','Chǔlǐ wèntí.','Xử lý vấn đề.'),
  _(734,'解决','jiějué','Giải quyết',4,'verb',15,'解决问题。','Jiějué wèntí.','Giải quyết vấn đề.'),
  _(735,'帮助','bāngzhù','Giúp đỡ',4,'verb',14,'帮助别人。','Bāngzhù biérén.','Giúp đỡ người khác.'),
  _(736,'支持','zhīchí','Ủng hộ',4,'verb',12,'支持你。','Zhīchí nǐ.','Ủng hộ bạn.'),
  _(737,'鼓励','gǔlì','Khuyến khích',4,'verb',17,'互相鼓励。','Hùxiāng gǔlì.','Khuyến khích nhau.'),
  _(738,'批评','pīpíng','Phê bình',4,'verb',12,'接受批评。','Jiēshòu pīpíng.','Tiếp nhận phê bình.'),
  _(739,'表扬','biǎoyáng','Biểu dương',4,'verb',13,'得到表扬。','Dédào biǎoyáng.','Được biểu dương.'),
  _(740,'道歉','dàoqiàn','Xin lỗi',4,'verb',16,'真诚道歉。','Zhēnchéng dàoqiàn.','Xin lỗi chân thành.'),
  _(741,'原谅','yuánliàng','Tha thứ',4,'verb',15,'请原谅。','Qǐng yuánliàng.','Xin thứ lỗi.'),
  _(742,'理解','lǐjiě','Hiểu',4,'verb',15,'我理解。','Wǒ lǐjiě.','Tôi hiểu.'),
  _(743,'误会','wùhuì','Hiểu lầm',4,'verb',10,'误会了。','Wùhuì le.','Hiểu lầm rồi.'),
  _(744,'沟通','gōutōng','Giao tiếp',4,'verb',12,'多沟通。','Duō gōutōng.','Giao tiếp nhiều.'),
  _(745,'交流','jiāoliú','Giao lưu',4,'verb',14,'交流文化。','Jiāoliú wénhuà.','Giao lưu văn hóa.'),
  _(746,'合作','hézuò','Hợp tác',4,'verb',10,'合作愉快。','Hézuò yúkuài.','Hợp tác vui vẻ.'),
  _(747,'商量','shāngliáng','Bàn bạc',4,'verb',15,'好好商量。','Hǎohāo shāngliáng.','Bàn bạc kỹ.'),
  _(748,'讨论','tǎolùn','Thảo luận',4,'verb',13,'讨论问题。','Tǎolùn wèntí.','Thảo luận vấn đề.'),
  _(749,'影响','yǐngxiǎng','Ảnh hưởng',4,'verb',17,'影响学习。','Yǐngxiǎng xuéxí.','Ảnh hưởng học tập.'),
  _(750,'作用','zuòyòng','Tác dụng',4,'noun',11,'有作用。','Yǒu zuòyòng.','Có tác dụng.'),
  _(751,'效果','xiàoguǒ','Hiệu quả',4,'noun',13,'效果很好。','Xiàoguǒ hěn hǎo.','Hiệu quả rất tốt.'),
  _(752,'结果','jiéguǒ','Kết quả',4,'noun',14,'结果不错。','Jiéguǒ bùcuò.','Kết quả không tồi.'),
  _(753,'原因','yuányīn','Nguyên nhân',4,'noun',14,'主要原因。','Zhǔyào yuányīn.','Nguyên nhân chính.'),
  _(754,'目的','mùdì','Mục đích',4,'noun',9,'什么目的？','Shénme mùdì?','Mục đích gì?'),
  _(755,'意义','yìyì','Ý nghĩa',4,'noun',11,'有意义的。','Yǒu yìyì de.','Có ý nghĩa.'),
  _(756,'价值','jiàzhí','Giá trị',4,'noun',12,'很有价值。','Hěn yǒu jiàzhí.','Rất có giá trị.'),
  _(757,'观点','guāndiǎn','Quan điểm',4,'noun',14,'个人观点。','Gèrén guāndiǎn.','Quan điểm cá nhân.'),
  _(758,'态度','tàidù','Thái độ',4,'noun',12,'态度很好。','Tàidù hěn hǎo.','Thái độ rất tốt.'),
  _(759,'行为','xíngwéi','Hành vi',4,'noun',11,'好的行为。','Hǎo de xíngwéi.','Hành vi tốt.'),
  _(760,'性格','xìnggé','Tính cách',4,'noun',13,'性格开朗。','Xìnggé kāilǎng.','Tính cách cởi mở.'),
  _(761,'特点','tèdiǎn','Đặc điểm',4,'noun',13,'有什么特点？','Yǒu shénme tèdiǎn?','Có đặc điểm gì?'),
  _(762,'优点','yōudiǎn','Ưu điểm',4,'noun',12,'很多优点。','Hěn duō yōudiǎn.','Nhiều ưu điểm.'),
  _(763,'缺点','quēdiǎn','Khuyết điểm',4,'noun',12,'有缺点。','Yǒu quēdiǎn.','Có khuyết điểm.'),
  _(764,'习惯','xíguàn','Thói quen',4,'noun',12,'改习惯。','Gǎi xíguàn.','Sửa thói quen.'),
  _(765,'传统','chuántǒng','Truyền thống',4,'noun',13,'传统文化。','Chuántǒng wénhuà.','Văn hóa truyền thống.'),
  _(766,'现代','xiàndài','Hiện đại',4,'adjective',12,'现代社会。','Xiàndài shèhuì.','Xã hội hiện đại.'),
  _(767,'古代','gǔdài','Cổ đại',4,'noun',10,'古代文化。','Gǔdài wénhuà.','Văn hóa cổ đại.'),
  _(768,'基础','jīchǔ','Cơ sở',4,'noun',13,'打好基础。','Dǎ hǎo jīchǔ.','Xây dựng cơ sở tốt.'),
  _(769,'根本','gēnběn','Căn bản',4,'adjective',13,'根本问题。','Gēnběn wèntí.','Vấn đề căn bản.'),
  _(770,'标准','biāozhǔn','Tiêu chuẩn',4,'noun',15,'达到标准。','Dádào biāozhǔn.','Đạt tiêu chuẩn.'),
  _(771,'条件','tiáojiàn','Điều kiện',4,'noun',12,'条件很好。','Tiáojiàn hěn hǎo.','Điều kiện rất tốt.'),
  _(772,'环境','huánjìng','Môi trường',4,'noun',13,'环境优美。','Huánjìng yōuměi.','Môi trường đẹp.'),
  _(773,'自然','zìrán','Tự nhiên',4,'noun',12,'大自然。','Dà zìrán.','Thiên nhiên.'),
  _(774,'空气','kōngqì','Không khí',4,'noun',12,'空气新鲜。','Kōngqì xīnxiān.','Không khí trong lành.'),
  _(775,'污染','wūrǎn','Ô nhiễm',4,'verb',11,'环境污染。','Huánjìng wūrǎn.','Ô nhiễm môi trường.'),
  _(776,'保护','bǎohù','Bảo vệ',4,'verb',13,'保护环境。','Bǎohù huánjìng.','Bảo vệ môi trường.'),
  _(777,'地球','dìqiú','Trái đất',4,'noun',14,'保护地球。','Bǎohù dìqiú.','Bảo vệ trái đất.'),
  _(778,'太阳','tàiyáng','Mặt trời',4,'noun',10,'太阳很大。','Tàiyáng hěn dà.','Mặt trời rất to.'),
  _(779,'月亮','yuèliang','Mặt trăng',4,'noun',9,'月亮很圆。','Yuèliang hěn yuán.','Trăng rất tròn.'),
  _(780,'星星','xīngxīng','Ngôi sao',4,'noun',13,'星星闪烁。','Xīngxīng shǎnshuò.','Sao lấp lánh.'),
  _(781,'森林','sēnlín','Rừng',4,'noun',16,'大森林。','Dà sēnlín.','Rừng lớn.'),
  _(782,'大海','dàhǎi','Biển',4,'noun',10,'去看大海。','Qù kàn dàhǎi.','Đi xem biển.'),
  _(783,'河流','héliú','Sông',4,'noun',13,'河流很长。','Héliú hěn cháng.','Sông rất dài.'),
  _(784,'山','shān','Núi',4,'noun',3,'爬山。','Pá shān.','Leo núi.'),
  _(785,'动物','dòngwù','Động vật',4,'noun',12,'喜欢动物。','Xǐhuān dòngwù.','Thích động vật.'),
  _(786,'植物','zhíwù','Thực vật',4,'noun',14,'绿色植物。','Lǜsè zhíwù.','Cây xanh.'),
  _(787,'花','huā','Hoa',4,'noun',7,'一朵花。','Yī duǒ huā.','Một bông hoa.'),
  _(788,'草','cǎo','Cỏ',4,'noun',9,'绿草。','Lǜ cǎo.','Cỏ xanh.'),
  _(789,'树','shù','Cây',4,'noun',9,'一棵树。','Yī kē shù.','Một cái cây.'),
  _(790,'阳光','yángguāng','Ánh nắng',4,'noun',12,'阳光明媚。','Yángguāng míngmèi.','Nắng đẹp.'),
  _(791,'影子','yǐngzi','Bóng',4,'noun',15,'看影子。','Kàn yǐngzi.','Nhìn bóng.'),
  _(792,'颜色','yánsè','Màu sắc',4,'noun',15,'五颜六色。','Wǔ yán liù sè.','Nhiều màu sắc.'),
  _(793,'红色','hóngsè','Đỏ',4,'noun',12,'红旗。','Hóng qí.','Cờ đỏ.'),
  _(794,'蓝色','lánsè','Xanh',4,'noun',16,'蓝蓝的天。','Lán lán de tiān.','Bầu trời xanh.'),
  _(795,'绿色','lǜsè','Xanh lá',4,'noun',17,'绿树。','Lǜ shù.','Cây xanh.'),
  _(796,'白色','báisè','Trắng',4,'noun',12,'白纸。','Bái zhǐ.','Giấy trắng.'),
  _(797,'黑色','hēisè','Đen',4,'noun',14,'黑夜。','Hēi yè.','Đêm tối.'),
  _(798,'黄色','huángsè','Vàng',4,'noun',16,'黄叶。','Huáng yè.','Lá vàng.'),
  _(799,'灰色','huīsè','Xám',4,'noun',16,'灰色的天。','Huīsè de tiān.','Trời xám.'),
  _(800,'紫色','zǐsè','Tím',4,'noun',16,'紫色的花。','Zǐsè de huā.','Hoa tím.'),
  _(801,'粉红色','fěnhóngsè','Hồng',4,'noun',21,'粉红色的裙子。','Fěnhóngsè de qúnzi.','Váy hồng.'),
  _(802,'手机','shǒujī','Điện thoại',4,'noun',11,'用手机。','Yòng shǒujī.','Dùng điện thoại.'),
  _(803,'充电器','chōngdiànqì','Sạc pin',4,'noun',14,'有充电器吗？','Yǒu chōngdiànqì ma?','Có sạc không?'),
  _(804,'电池','diànchí','Pin',4,'noun',9,'换电池。','Huàn diànchí.','Thay pin.'),
  _(805,'声音','shēngyīn','Âm thanh',4,'noun',12,'声音很大。','Shēngyīn hěn dà.','Âm thanh rất to.'),
  _(806,'音乐','yīnyuè','Âm nhạc',4,'noun',11,'听音乐。','Tīng yīnyuè.','Nghe nhạc.'),
  _(807,'电影','diànyǐng','Phim',4,'noun',12,'看电影。','Kàn diànyǐng.','Xem phim.'),
  _(808,'电视','diànshì','Tivi',4,'noun',13,'看电视。','Kàn diànshì.','Xem tivi.'),
  _(809,'节目','jiémù','Chương trình',4,'noun',10,'电视节目。','Diànshì jiémù.','Chương trình tivi.'),
  _(810,'新闻','xīnwén','Tin tức',4,'noun',13,'看新闻。','Kàn xīnwén.','Xem tin tức.'),
  _(811,'报纸','bàozhǐ','Báo',4,'noun',12,'看报纸。','Kàn bàozhǐ.','Đọc báo.'),
  _(812,'杂志','zázhì','Tạp chí',4,'noun',10,'看杂志。','Kàn zázhì.','Đọc tạp chí.'),
  _(813,'小说','xiǎoshuō','Tiểu thuyết',4,'noun',9,'看小说。','Kàn xiǎoshuō.','Đọc tiểu thuyết.'),
  _(814,'文章','wénzhāng','Bài văn',4,'noun',8,'写文章。','Xiě wénzhāng.','Viết bài.'),
  _(815,'内容','nèiróng','Nội dung',4,'noun',9,'内容丰富。','Nèiróng fēngfù.','Nội dung phong phú.'),
  _(816,'题目','tímù','Đề mục',4,'noun',10,'考试题目。','Kǎoshì tímù.','Đề thi.'),
  _(817,'材料','cáiliào','Tài liệu',4,'noun',9,'看材料。','Kàn cáiliào.','Xem tài liệu.'),
  _(818,'资料','zīliào','Tư liệu',4,'noun',13,'收集资料。','Shōují zīliào.','Thu thập tư liệu.'),
  _(819,'记录','jìlù','Ghi lại',4,'verb',12,'记录下来。','Jìlù xiàlái.','Ghi lại.'),
  _(820,'整理','zhěnglǐ','Sắp xếp',4,'verb',20,'整理房间。','Zhěnglǐ fángjiān.','Dọn phòng.'),
  _(821,'计划','jìhuà','Kế hoạch',4,'noun',10,'有计划。','Yǒu jìhuà.','Có kế hoạch.'),
  _(822,'目标','mùbiāo','Mục tiêu',4,'noun',10,'达到目标。','Dádào mùbiāo.','Đạt mục tiêu.'),
  _(823,'准备','zhǔnbèi','Chuẩn bị',4,'verb',17,'做准备。','Zuò zhǔnbèi.','Chuẩn bị.'),
  _(824,'练习','liànxí','Luyện tập',4,'verb',15,'做练习。','Zuò liànxí.','Làm bài luyện.'),
  _(825,'复习','fùxí','Ôn tập',4,'verb',14,'复习功课。','Fùxí gōngkè.','Ôn bài.'),
  _(826,'预习','yùxí','Xem trước',4,'verb',13,'预习新课。','Yùxí xīn kè.','Xem trước bài mới.'),
  _(827,'上','shàng','Lên lớp',4,'verb',3,'上课。','Shàngkè.','Lên lớp.'),
  _(828,'下','xià','Tan học',4,'verb',4,'下课。','Xiàkè.','Tan học.'),
  _(829,'放','fàng','Nghỉ',4,'verb',8,'放学了。','Fàngxué le.','Tan trường rồi.'),
  _(830,'请假','qǐngjià','Xin phép nghỉ',4,'verb',16,'请假一天。','Qǐngjià yī tiān.','Xin nghỉ một ngày.'),
  _(831,'迟到','chídào','Đến muộn',4,'verb',5,'别迟到。','Bié chídào.','Đừng đến muộn.'),
  _(832,'早退','zǎotuì','Về sớm',4,'verb',10,'别早退。','Bié zǎotuì.','Đừng về sớm.'),
  _(833,'缺课','quēkè','Nghỉ học',4,'verb',13,'缺课了。','Quēkè le.','Nghỉ học rồi.'),
  _(834,'补课','bǔkè','Học bù',4,'verb',12,'补课。','Bǔkè.','Học bù.'),
  _(835,'辅导','fǔdǎo','Phụ đạo',4,'verb',15,'辅导学习。','Fǔdǎo xuéxí.','Phụ đạo học tập.'),
  _(836,'考试','kǎoshì','Thi',4,'noun',15,'期末考试。','Qímò kǎoshì.','Thi cuối kỳ.'),
  _(837,'成绩','chéngjì','Điểm',4,'noun',11,'考试成绩。','Kǎoshì chéngjì.','Điểm thi.'),
  _(838,'分数','fēnshù','Điểm số',4,'noun',12,'分数很高。','Fēnshù hěn gāo.','Điểm rất cao.'),
  _(839,'及格','jígé','Đỗ',4,'verb',9,'及格了。','Jígé le.','Đỗ rồi.'),
  _(840,'优秀','yōuxiù','Xuất sắc',4,'adjective',12,'成绩优秀。','Chéngjì yōuxiù.','Thành tích xuất sắc.'),
  _(841,'良好','liánghǎo','Tốt',4,'adjective',11,'成绩良好。','Chéngjì liánghǎo.','Thành tích tốt.'),
  _(842,'中等','zhōngděng','Trung bình',4,'adjective',11,'中等水平。','Zhōngděng shuǐpíng.','Trình độ trung bình.'),
  _(843,'差','chà','Kém',4,'adjective',9,'成绩差。','Chéngjì chà.','Thành tích kém.'),
  _(844,'进步','jìnbù','Tiến bộ',4,'verb',12,'进步很大。','Jìnbù hěn dà.','Tiến bộ rất lớn.'),
  _(845,'退步','tuìbù','Thụt lùi',4,'verb',13,'退步了。','Tuìbù le.','Thụt lùi rồi.'),
  _(846,'努力','nǔlì','Cố gắng',4,'adjective',13,'更加努力。','Gèngjiā nǔlì.','Cố gắng hơn.'),
  _(847,'刻苦','kèkǔ','Chăm chỉ',4,'adjective',14,'刻苦学习。','Kèkǔ xuéxí.','Chăm chỉ học.'),
  _(848,'认真','rènzhēn','Nghiêm túc',4,'adjective',14,'认真工作。','Rènzhēn gōngzuò.','Làm việc nghiêm túc.'),
  _(849,'仔细','zǐxì','Cẩn thận',4,'adjective',15,'仔细检查。','Zǐxì jiǎnchá.','Kiểm tra cẩn thận.'),
  _(850,'马虎','mǎhu','Cẩu thả',4,'adjective',8,'别马虎。','Bié mǎhu.','Đừng cẩu thả.'),
  _(851,'工作','gōngzuò','Công việc',4,'noun',5,'找到工作。','Zhǎodào gōngzuò.','Tìm được việc.'),
  _(852,'职业','zhíyè','Nghề nghiệp',4,'noun',13,'选择职业。','Xuǎnzé zhíyè.','Chọn nghề.'),
  _(853,'行业','hángyè','Ngành',4,'noun',12,'什么行业？','Shénme hángyè?','Ngành gì?'),
  _(854,'单位','dānwèi','Đơn vị',4,'noun',10,'在单位。','Zài dānwèi.','Ở cơ quan.'),
  _(855,'部门','bùmén','Phòng ban',4,'noun',13,'在哪个部门？','Zài nǎge bùmén?','Ở phòng nào?'),
  _(856,'同事','tóngshì','Đồng nghiệp',4,'noun',10,'我的同事。','Wǒ de tóngshì.','Đồng nghiệp của tôi.'),
  _(857,'领导','lǐngdǎo','Lãnh đạo',4,'noun',13,'公司领导。','Gōngsī lǐngdǎo.','Lãnh đạo công ty.'),
  _(858,'员工','yuángōng','Nhân viên',4,'noun',11,'公司员工。','Gōngsī yuángōng.','Nhân viên công ty.'),
  _(859,'老板','lǎobǎn','Ông chủ',4,'noun',11,'老板很好。','Lǎobǎn hěn hǎo.','Ông chủ rất tốt.'),
  _(860,'面试','miànshì','Phỏng vấn',4,'verb',14,'去面试。','Qù miànshì.','Đi phỏng vấn.'),
  _(861,'录取','lùqǔ','Trúng tuyển',4,'verb',12,'被录取了。','Bèi lùqǔ le.','Trúng tuyển rồi.'),
  _(862,'应聘','yìngpìn','Ứng tuyển',4,'verb',12,'应聘工作。','Yìngpìn gōngzuò.','Ứng tuyển việc.'),
  _(863,'辞职','cízhí','Từ chức',4,'verb',13,'辞职了。','Cízhí le.','Từ chức rồi.'),
  _(864,'退休','tuìxiū','Nghỉ hưu',4,'verb',13,'退休了。','Tuìxiū le.','Nghỉ hưu rồi.'),
  _(865,'加班','jiābān','Tăng ca',4,'verb',9,'加班工作。','Jiābān gōngzuò.','Làm thêm giờ.'),
  _(866,'请假','qǐngjià','Xin nghỉ',4,'verb',16,'请假两天。','Qǐngjià liǎng tiān.','Xin nghỉ hai ngày.'),
  _(867,'出差','chūchāi','Đi công tác',4,'verb',10,'出差北京。','Chūchāi Běijīng.','Đi công tác Bắc Kinh.'),
  _(868,'开会','kāihuì','Họp',4,'verb',10,'开会中。','Kāihuì zhōng.','Đang họp.'),
  _(869,'会议','huìyì','Hội nghị',4,'noun',9,'参加会议。','Cānjiā huìyì.','Tham gia hội nghị.'),
  _(870,'通知','tōngzhī','Thông báo',4,'verb',14,'通知大家。','Tōngzhī dàjiā.','Thông báo mọi người.'),
  _(871,'电话','diànhuà','Điện thoại',4,'noun',10,'打电话。','Dǎ diànhuà.','Gọi điện.'),
  _(872,'接电话','jiē diànhuà','Nghe điện thoại',4,'verb',18,'接电话。','Jiē diànhuà.','Nghe điện thoại.'),
  _(873,'挂电话','guà diànhuà','Tắt máy',4,'verb',15,'挂电话了。','Guà diànhuà le.','Tắt máy rồi.'),
  _(874,'留言','liúyán','Để lại lời nhắn',4,'verb',12,'请留言。','Qǐng liúyán.','Xin để lại lời nhắn.'),
  _(875,'回信','huíxìn','Hồi âm',4,'verb',13,'尽快回信。','Jǐnkuài huíxìn.','Sớm hồi âm.'),
  _(876,'联系','liánxì','Liên lạc',4,'verb',12,'保持联系。','Bǎochí liánxì.','Giữ liên lạc.'),
  _(877,'见面','jiànmiàn','Gặp mặt',4,'verb',11,'明天见面。','Míngtiān jiànmiàn.','Mai gặp nhau.'),
  _(878,'约会','yuēhuì','Hẹn hò',4,'verb',10,'有约会。','Yǒu yuēhuì.','Có hẹn.'),
  _(879,'邀请','yāoqǐng','Mời',4,'verb',13,'邀请朋友。','Yāoqǐng péngyǒu.','Mời bạn bè.'),
  _(880,'拜访','bàifǎng','Thăm hỏi',4,'verb',12,'拜访老师。','Bàifǎng lǎoshī.','Thăm giáo viên.'),
  _(881,'参观','cānguān','Tham quan',4,'verb',12,'参观博物馆。','Cānguān bówùguǎn.','Tham quan bảo tàng.'),
  _(882,'旅游','lǚyóu','Du lịch',4,'verb',16,'去旅游。','Qù lǚyóu.','Đi du lịch.'),
  _(883,'出发','chūfā','Xuất phát',4,'verb',11,'出发了。','Chūfā le.','Đi rồi.'),
  _(884,'到达','dàodá','Đến nơi',4,'verb',14,'安全到达。','Ānquán dàodá.','Đến nơi an toàn.'),
  _(885,'经过','jīngguò','Đi qua',4,'verb',13,'经过北京。','Jīngguò Běijīng.','Đi qua Bắc Kinh.'),
  _(886,'路过','lùguò','Đi ngang',4,'verb',13,'路过上海。','Lùguò Shànghǎi.','Đi ngang Thượng Hải.'),
  _(887,'出发','chūfā','Khởi hành',4,'verb',11,'早上出发。','Zǎoshang chūfā.','Khởi hành sáng.'),
  _(888,'行李','xíngli','Hành lý',4,'noun',12,'拿行李。','Ná xíngli.','Lấy hành lý.'),
  _(889,'护照','hùzhào','Hộ chiếu',4,'noun',15,'带护照。','Dài hùzhào.','Mang hộ chiếu.'),
  _(890,'签证','qiānzhèng','Visa',4,'noun',15,'办签证。','Bàn qiānzhèng.','Làm visa.'),
  _(891,'机票','jīpiào','Vé máy bay',4,'noun',10,'买机票。','Mǎi jīpiào.','Mua vé máy bay.'),
  _(892,'火车票','huǒchēpiào','Vé tàu',4,'noun',16,'买火车票。','Mǎi huǒchēpiào.','Mua vé tàu.'),
  _(893,'售票处','shòupiàochù','Quầy vé',4,'noun',16,'在售票处。','Zài shòupiàochù.','Ở quầy vé.'),
  _(894,'出口','chūkǒu','Lối ra',4,'noun',7,'出口在哪？','Chūkǒu zài nǎ?','Lối ra ở đâu?'),
  _(895,'入口','rùkǒu','Lối vào',4,'noun',5,'入口在这。','Rùkǒu zài zhè.','Lối vào ở đây.'),
  _(896,'站台','zhàntái','Sân ga',4,'noun',13,'在站台等。','Zài zhàntái děng.','Đợi ở sân ga.'),
  _(897,'行李架','xínglijià','Giá để hành lý',4,'noun',16,'放行李架。','Fàng xínglijià.','Đặt trên giá hành lý.'),
  _(898,'宾馆','bīnguǎn','Khách sạn',4,'noun',14,'住宾馆。','Zhù bīnguǎn.','Ở khách sạn.'),
  _(899,'前台','qiántái','Quầy lễ tân',4,'noun',13,'去前台。','Qù qiántái.','Đến quầy lễ tân.'),
  _(900,'房间','fángjiān','Phòng',4,'noun',14,'订房间。','Dìng fángjiān.','Đặt phòng.'),
  _(901,'钥匙','yàoshi','Chìa khóa',4,'noun',12,'拿钥匙。','Ná yàoshi.','Lấy chìa khóa.'),
  _(902,'退房','tuìfáng','Trả phòng',4,'verb',14,'退房时间。','Tuìfáng shíjiān.','Giờ trả phòng.'),
  _(903,'入住','rùzhù','Nhận phòng',4,'verb',9,'办理入住。','Bànlǐ rùzhù.','Làm thủ tục nhận phòng.'),
  _(904,'手续','shǒuxù','Thủ tục',4,'noun',11,'办手续。','Bàn shǒuxù.','Làm thủ tục.'),
  _(905,'护照','hùzhào','Hộ chiếu',4,'noun',15,'检查护照。','Jiǎnchá hùzhào.','Kiểm tra hộ chiếu.'),
  _(906,'签证','qiānzhèng','Visa',4,'noun',15,'办签证。','Bàn qiānzhèng.','Làm visa.'),
  _(907,'海关','hǎiguān','Hải quan',4,'noun',14,'通过海关。','Tōngguò hǎiguān.','Qua hải quan.'),
  _(908,'申报','shēnbào','Khai báo',4,'verb',12,'海关申报。','Hǎiguān shēnbào.','Khai báo hải quan.'),
  _(909,'税','shuì','Thuế',4,'noun',12,'交税。','Jiāo shuì.','Nộp thuế.'),
  _(910,'免税','miǎnshuì','Miễn thuế',4,'adjective',16,'免税店。','Miǎnshuì diàn.','Cửa hàng miễn thuế.'),
  _(911,'兑换','duìhuàn','Đổi tiền',4,'verb',14,'兑换外币。','Duìhuàn wàibì.','Đổi ngoại tệ.'),
  _(912,'汇率','huìlǜ','Tỷ giá',4,'noun',11,'汇率是多少？','Huìlǜ shì duōshao?','Tỷ giá là bao nhiêu?'),
  _(913,'人民币','rénmínbì','Nhân dân tệ',4,'noun',15,'换人民币。','Huàn rénmínbì.','Đổi nhân dân tệ.'),
  _(914,'美元','měiyuán','Đô la Mỹ',4,'noun',9,'一百美元。','Yībǎi měiyuán.','100 đô la.'),
  _(915,'欧元','ōuyuán','Euro',4,'noun',10,'欧元区。','Ōuyuán qū.','Khu vực Euro.'),
  _(916,'日元','rìyuán','Yên Nhật',4,'noun',7,'一万日元。','Yī wàn rìyuán.','1 vạn yên.'),
  _(917,'地方','dìfang','Địa phương',4,'noun',12,'好地方。','Hǎo dìfang.','Nơi tốt.'),
  _(918,'当地','dāngdì','Địa phương',4,'noun',11,'当地人。','Dāngdì rén.','Người địa phương.'),
  _(919,'外地','wàidì','Nơi khác',4,'noun',9,'外地人。','Wàidì rén.','Người từ nơi khác.'),
  _(920,'外地','wàidì','Tỉnh ngoài',4,'noun',9,'在外地工作。','Zài wàidì gōngzuò.','Làm việc ở tỉnh ngoài.'),
  _(921,'地址','dìzhǐ','Địa chỉ',4,'noun',10,'你的地址。','Nǐ de dìzhǐ.','Địa chỉ của bạn.'),
  _(922,'路','lù','Đường',4,'noun',13,'哪条路？','Nǎ tiáo lù?','Đường nào?'),
  _(923,'街','jiē','Phố',4,'noun',12,'逛街。','Guàng jiē.','Đi phố.'),
  _(924,'路口','lùkǒu','Ngã tư',4,'noun',15,'在路口左转。','Zài lùkǒu zuǒzhuǎn.','Rẽ trái ở ngã tư.'),
  _(925,'拐','guǎi','Rẽ',4,'verb',10,'拐弯。','Guǎi wān.','Rẽ.'),
  _(926,'转','zhuǎn','Quẹo',4,'verb',9,'右转。','Yòu zhuǎn.','Rẽ phải.'),
  _(927,'往前','wǎngqián','Về phía trước',4,'adverb',13,'一直往前。','Yīzhí wǎngqián.','Cứ đi thẳng.'),
  _(928,'过马路','guò mǎlù','Qua đường',4,'verb',14,'过马路小心。','Guò mǎlù xiǎoxīn.','Qua đường cẩn thận.'),
  _(929,'交通','jiāotōng','Giao thông',4,'noun',12,'交通方便。','Jiāotōng fāngbiàn.','Giao thông thuận tiện.'),
  _(930,'信号灯','xìnhàodēng','Đèn tín hiệu',4,'noun',17,'看信号灯。','Kàn xìnhàodēng.','Nhìn đèn tín hiệu.'),
  _(931,'加油站','jiāyóuzhàn','Trạm xăng',4,'noun',18,'去加油站。','Qù jiāyóuzhàn.','Đi trạm xăng.'),
  _(932,'停车场','tíngchēchǎng','Bãi đỗ xe',4,'noun',16,'在停车场。','Zài tíngchēchǎng.','Ở bãi đỗ xe.'),
  _(933,'红灯','hóngdēng','Đèn đỏ',4,'noun',13,'红灯停。','Hóngdēng tíng.','Đèn đỏ dừng.'),
  _(934,'绿灯','lǜdēng','Đèn xanh',4,'noun',13,'绿灯行。','Lǜdēng xíng.','Đèn xanh đi.'),
  _(935,'发生','fāshēng','Xảy ra',4,'verb',12,'发生事故。','Fāshēng shìgù.','Xảy ra tai nạn.'),
  _(936,'事故','shìgù','Tai nạn',4,'noun',12,'交通事故。','Jiāotōng shìgù.','Tai nạn giao thông.'),
  _(937,'堵车','dǔchē','Tắc đường',4,'verb',15,'又堵车了。','Yòu dǔchē le.','Lại tắc đường rồi.'),
  _(938,'修车','xiūchē','Sửa xe',4,'verb',15,'去修车。','Qù xiūchē.','Đi sửa xe.'),
  _(939,'加油','jiāyóu','Đổ xăng / Cố lên',4,'verb',9,'加油！','Jiāyóu!','Cố lên!'),
  _(940,'走路','zǒulù','Đi bộ',4,'verb',16,'走路去。','Zǒulù qù.','Đi bộ.'),
  _(941,'爬山','páshān','Leo núi',4,'verb',12,'去爬山。','Qù páshān.','Đi leo núi.'),
  _(942,'散步','sànbù','Đi dạo',4,'verb',16,'去散步。','Qù sànbù.','Đi dạo.'),
  _(943,'跑步','pǎobù','Chạy',4,'verb',16,'去跑步。','Qù pǎobù.','Đi chạy.'),
  _(944,'打太极拳','dǎ tàijíquán','Tập Thái Cực Quyền',4,'verb',20,'打太极拳。','Dǎ tàijíquán.','Tập Thái Cực Quyền.'),
  _(945,'锻炼','duànliàn','Tập luyện',4,'verb',17,'每天锻炼。','Měitiān duànliàn.','Tập mỗi ngày.'),
  _(946,'身体','shēntǐ','Cơ thể',4,'noun',11,'身体健康。','Shēntǐ jiànkāng.','Sức khỏe tốt.'),
  _(947,'健康','jiànkāng','Sức khỏe',4,'noun',15,'祝您健康。','Zhù nín jiànkāng.','Chúc ngài sức khỏe.'),
  _(948,'锻炼身体','duànliàn shēntǐ','Rèn luyện thân thể',4,'verb',22,'经常锻炼身体。','Jīngcháng duànliàn shēntǐ.','Thường xuyên rèn luyện.'),
  _(949,'减肥','jiǎnféi','Giảm béo',4,'verb',14,'正在减肥。','Zhèngzài jiǎnféi.','Đang giảm béo.'),
  _(950,'胖','pàng','Béo',4,'adjective',9,'变胖了。','Biàn pàng le.','Béo lên rồi.'),
  _(951,'瘦','shòu','Gầy',4,'adjective',14,'太瘦了。','Tài shòu le.','Gầy quá.'),
  _(952,'重','zhòng','Nặng',4,'adjective',9,'很重。','Hěn zhòng.','Rất nặng.'),
  _(953,'轻','qīng','Nhẹ',4,'adjective',9,'很轻。','Hěn qīng.','Rất nhẹ.'),
  _(954,'称','chēng','Cân',4,'verb',10,'称一下。','Chēng yīxià.','Cân một chút.'),
  _(955,'检查','jiǎnchá','Kiểm tra',4,'verb',16,'检查身体。','Jiǎnchá shēntǐ.','Kiểm tra sức khỏe.'),
  _(956,'化验','huàyàn','Xét nghiệm',4,'verb',12,'化验血。','Huàyàn xiě.','Xét nghiệm máu.'),
  _(957,'结果','jiéguǒ','Kết quả',4,'noun',14,'检查结果。','Jiǎnchá jiéguǒ.','Kết quả kiểm tra.'),
  _(958,'正常','zhèngcháng','Bình thường',4,'adjective',12,'一切正常。','Yīqiè zhèngcháng.','Mọi thứ bình thường.'),
  _(959,'手术','shǒushù','Phẫu thuật',4,'noun',11,'做手术。','Zuò shǒushù.','Làm phẫu thuật.'),
  _(960,'住院','zhùyuàn','Nằm viện',4,'verb',15,'住院三天。','Zhùyuàn sān tiān.','Nằm viện ba ngày.'),
  _(961,'出院','chūyuàn','Ra viện',4,'verb',13,'出院了。','Chūyuàn le.','Ra viện rồi.'),
  _(962,'恢复','huīfù','Hồi phục',4,'verb',14,'恢复健康。','Huīfù jiànkāng.','Hồi phục sức khỏe.'),
  _(963,'药方','yàofāng','Đơn thuốc',4,'noun',13,'开药方。','Kāi yàofāng.','Kê đơn thuốc.'),
  _(964,'吃药','chī yào','Uống thuốc',4,'verb',10,'按时吃药。','Ànshí chī yào.','Uống thuốc đúng giờ.'),
  _(965,'打针','dǎzhēn','Tiêm',4,'verb',11,'打针了。','Dǎzhēn le.','Tiêm rồi.'),
  _(966,'量体温','liáng tǐwēn','Đo nhiệt độ',4,'verb',17,'量体温。','Liáng tǐwēn.','Đo nhiệt độ.'),
  _(967,'抽血','chōuxiě','Lấy máu',4,'verb',12,'抽血化验。','Chōuxiě huàyàn.','Lấy máu xét nghiệm.'),
  _(968,'营养','yíngyǎng','Dinh dưỡng',4,'noun',15,'有营养。','Yǒu yíngyǎng.','Có dinh dưỡng.'),
  _(969,'维生素','wéishēngsù','Vitamin',4,'noun',19,'补充维生素。','Bǔchōng wéishēngsù.','Bổ sung vitamin.'),
  _(970,'休息','xiūxi','Nghỉ',4,'verb',12,'好好休息。','Hǎohāo xiūxi.','Nghỉ ngơi tốt.'),
];

// ─── HSK 5–6: id 971–1000 (30 từ mới) ──────────────────────
export const hsk5 = [
  _(971,'遗产','yíchǎn','Di sản',5,'noun',14,'文化遗产。','Wénhuà yíchǎn.','Di sản văn hóa.'),
  _(972,'投资','tóuzī','Đầu tư',5,'verb',14,'投资教育。','Tóuzī jiàoyù.','Đầu tư giáo dục.'),
  _(973,'贸易','màoyì','Mậu dịch',5,'noun',14,'国际贸易。','Guójì màoyì.','Mậu dịch quốc tế.'),
  _(974,'贷款','dàikuǎn','Vay tiền',5,'verb',13,'银行贷款。','Yínháng dàikuǎn.','Vay ngân hàng.'),
  _(975,'利息','lìxī','Lãi suất',5,'noun',12,'利息很高。','Lìxī hěn gāo.','Lãi suất cao.'),
  _(976,'成本','chéngběn','Chi phí',5,'noun',10,'降低成本。','Jiàngdī chéngběn.','Giảm chi phí.'),
  _(977,'利润','lìrùn','Lợi nhuận',5,'noun',13,'利润很高。','Lìrùn hěn gāo.','Lợi nhuận cao.'),
  _(978,'资金','zījīn','Vốn',5,'noun',12,'需要资金。','Xūyào zījīn.','Cần vốn.'),
  _(979,'预算','yùsuàn','Ngân sách',5,'noun',13,'做预算。','Zuò yùsuàn.','Làm ngân sách.'),
  _(980,'股票','gǔpiào','Cổ phiếu',5,'noun',13,'买股票。','Mǎi gǔpiào.','Mua cổ phiếu.'),
  _(981,'期货','qīhuò','Hàng hóa kỳ hạn',5,'noun',14,'期货交易。','Qīhuò jiāoyì.','Giao dịch kỳ hạn.'),
  _(982,'商业','shāngyè','Thương mại',5,'noun',14,'商业中心。','Shāngyè zhōngxīn.','Trung tâm thương mại.'),
  _(983,'企业','qǐyè','Doanh nghiệp',5,'noun',11,'私人企业。','Sīrén qǐyè.','Doanh nghiệp tư nhân.'),
  _(984,'民营','mínyíng','Dân doanh',5,'adjective',14,'民营企业。','Mínyíng qǐyè.','Doanh nghiệp dân doanh.'),
  _(985,'国有','guóyǒu','Quốc doanh',5,'adjective',12,'国有企业。','Guóyǒu qǐyè.','Doanh nghiệp nhà nước.'),
  _(986,'管理','guǎnlǐ','Quản lý',5,'verb',18,'企业管理。','Qǐyè guǎnlǐ.','Quản lý doanh nghiệp.'),
  _(987,'经营','jīngyíng','Kinh doanh',5,'verb',14,'经营公司。','Jīngyíng gōngsī.','Kinh doanh công ty.'),
  _(988,'销售','xiāoshòu','Bán hàng',5,'verb',16,'销售经理。','Xiāoshòu jīnglǐ.','Giám đốc bán hàng.'),
  _(989,'市场','shìchǎng','Thị trường',5,'noun',11,'市场调查。','Shìchǎng diàochá.','Điều tra thị trường.'),
  _(990,'竞争','jìngzhēng','Cạnh tranh',5,'verb',15,'市场竞争。','Shìchǎng jìngzhēng.','Cạnh tranh thị trường.'),
  _(991,'合作','hézuò','Hợp tác',5,'verb',10,'国际合作。','Guójì hézuò.','Hợp tác quốc tế.'),
  _(992,'法律','fǎlǜ','Pháp luật',5,'noun',12,'遵守法律。','Zūnshǒu fǎlǜ.','Tuân thủ pháp luật.'),
  _(993,'合同','hétong','Hợp đồng',5,'noun',10,'签合同。','Qiān hétong.','Ký hợp đồng.'),
  _(994,'协议','xiéyì','Hiệp nghị',5,'noun',11,'达成协议。','Dáchéng xiéyì.','Đạt được hiệp nghị.'),
  _(995,'产权','chǎnquán','Quyền sở hữu',5,'noun',10,'知识产权。','Zhīshi chǎnquán.','Sở hữu trí tuệ.'),
  _(996,'专利','zhuānlì','Bằng sáng chế',5,'noun',12,'申请专利。','Shēnqǐng zhuānlì.','Xin bằng sáng chế.'),
  _(997,'品牌','pǐnpái','Thương hiệu',5,'noun',13,'知名品牌。','Zhīmíng pǐnpái.','Thương hiệu nổi tiếng.'),
  _(998,'广告','guǎnggào','Quảng cáo',5,'noun',11,'做广告。','Zuò guǎnggào.','Làm quảng cáo.'),
  _(999,'宣传','xuānchuán','Tuyên truyền',5,'verb',15,'宣传活动。','Xuānchuán huódòng.','Hoạt động tuyên truyền.'),
  _(1000,'策划','cèhuà','Lên kế hoạch',5,'verb',15,'策划活动。','Cèhuà huódòng.','Lên kế hoạch hoạt động.'),
];
